//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPAdditionalInformation.h"


@implementation SAPAdditionalInformation
@synthesize key;
@synthesize value;

+ (SAPAdditionalInformation *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPAdditionalInformation* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"key"])
             {
                if([SAPHelper isValue:__node name:@"key"])
                {
                    self.key = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"value"])
             {
                if([SAPHelper isValue:__node name:@"value"])
                {
                    if(self.value == nil)
                    {
                        self.value =[NSMutableArray array];
                    }
                    [self.value addObject:[__node stringValue]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __keyItemElement=[__request writeElement:key type:[NSString class] name:@"key" URI:@"" parent:__parent skipNullProperty:NO];
    if(__keyItemElement!=nil)
    {
        [__keyItemElement setStringValue:self.key];
    }
            
    if(self.value!=nil)
    {
        for (NSString* __item in self.value) {
            DDXMLElement* __valueItemElement=[__request writeElement:value type:[NSString class] name:@"value" URI:@"" parent:__parent skipNullProperty:NO];
            if(__valueItemElement!=nil)
            {
                [__valueItemElement setStringValue:__item];
            }
        }
    }


}
@end
