//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPAuthenticationRealm.h"


@implementation SAPAuthenticationRealm
@synthesize SourceID;
@synthesize MessageID;
@synthesize MessageType;
@synthesize TimeStamp;

+ (SAPAuthenticationRealm *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPAuthenticationRealm* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"SourceID"])
             {
                if([SAPHelper isValue:__node name:@"SourceID"])
                {
                    self.SourceID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"MessageID"])
             {
                if([SAPHelper isValue:__node name:@"MessageID"])
                {
                    self.MessageID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"MessageType"])
             {
                if([SAPHelper isValue:__node name:@"MessageType"])
                {
                    self.MessageType = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"TimeStamp"])
             {
                if([SAPHelper isValue:__node name:@"TimeStamp"])
                {
                    self.TimeStamp = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __SourceIDItemElement=[__request writeElement:SourceID type:[NSString class] name:@"SourceID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SourceIDItemElement!=nil)
    {
        [__SourceIDItemElement setStringValue:self.SourceID];
    }
            
    DDXMLElement* __MessageIDItemElement=[__request writeElement:MessageID type:[NSString class] name:@"MessageID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__MessageIDItemElement!=nil)
    {
        [__MessageIDItemElement setStringValue:self.MessageID];
    }
            
    DDXMLElement* __MessageTypeItemElement=[__request writeElement:MessageType type:[NSString class] name:@"MessageType" URI:@"" parent:__parent skipNullProperty:NO];
    if(__MessageTypeItemElement!=nil)
    {
        [__MessageTypeItemElement setStringValue:self.MessageType];
    }
            
    DDXMLElement* __TimeStampItemElement=[__request writeElement:TimeStamp type:[NSString class] name:@"TimeStamp" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TimeStampItemElement!=nil)
    {
        [__TimeStampItemElement setStringValue:self.TimeStamp];
    }


}
@end
