//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPBookingStatusOperationBody.h"


@implementation SAPBookingStatusOperationBody
@synthesize BookingReferenceId;

+ (SAPBookingStatusOperationBody *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPBookingStatusOperationBody* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"BookingReferenceId"])
             {
                if([SAPHelper isValue:__node name:@"BookingReferenceId"])
                {
                    self.BookingReferenceId = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __BookingReferenceIdItemElement=[__request writeElement:BookingReferenceId type:[NSString class] name:@"BookingReferenceId" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BookingReferenceIdItemElement!=nil)
    {
        [__BookingReferenceIdItemElement setStringValue:self.BookingReferenceId];
    }


}
@end
