//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPCustomExcursionOperation.h"


@implementation SAPCustomExcursionOperation
@synthesize Adults;
@synthesize Children;
@synthesize Infant;
@synthesize Senior;

+ (SAPCustomExcursionOperation *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPCustomExcursionOperation* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"Adults"])
             {
                if([SAPHelper isValue:__node name:@"Adults"])
                {
                    self.Adults = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Children"])
             {
                if([SAPHelper isValue:__node name:@"Children"])
                {
                    self.Children = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Infant"])
             {
                if([SAPHelper isValue:__node name:@"Infant"])
                {
                    self.Infant = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Senior"])
             {
                if([SAPHelper isValue:__node name:@"Senior"])
                {
                    self.Senior = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __AdultsItemElement=[__request writeElement:Adults type:[NSNumber class] name:@"Adults" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AdultsItemElement!=nil)
    {
        [__AdultsItemElement setStringValue:[SAPHelper getStringFromNumber:self.Adults]];
    }
            
    DDXMLElement* __ChildrenItemElement=[__request writeElement:Children type:[NSNumber class] name:@"Children" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ChildrenItemElement!=nil)
    {
        [__ChildrenItemElement setStringValue:[SAPHelper getStringFromNumber:self.Children]];
    }
            
    DDXMLElement* __InfantItemElement=[__request writeElement:Infant type:[NSNumber class] name:@"Infant" URI:@"" parent:__parent skipNullProperty:YES];
    if(__InfantItemElement!=nil)
    {
        [__InfantItemElement setStringValue:[SAPHelper getStringFromNumber:self.Infant]];
    }
            
    DDXMLElement* __SeniorItemElement=[__request writeElement:Senior type:[NSNumber class] name:@"Senior" URI:@"" parent:__parent skipNullProperty:YES];
    if(__SeniorItemElement!=nil)
    {
        [__SeniorItemElement setStringValue:[SAPHelper getStringFromNumber:self.Senior]];
    }


}
@end
