//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPCancellationDetailsBody.h"


@implementation SAPCancellationDetailsBody
@synthesize userName;
@synthesize password;
@synthesize CID;
@synthesize ConfirmationID;
@synthesize RefferenceID;

+ (SAPCancellationDetailsBody *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPCancellationDetailsBody* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"userName"])
             {
                if([SAPHelper isValue:__node name:@"userName"])
                {
                    self.userName = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"password"])
             {
                if([SAPHelper isValue:__node name:@"password"])
                {
                    self.password = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"CID"])
             {
                if([SAPHelper isValue:__node name:@"CID"])
                {
                    self.CID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ConfirmationID"])
             {
                if([SAPHelper isValue:__node name:@"ConfirmationID"])
                {
                    self.ConfirmationID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"RefferenceID"])
             {
                if([SAPHelper isValue:__node name:@"RefferenceID"])
                {
                    self.RefferenceID = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __userNameItemElement=[__request writeElement:userName type:[NSString class] name:@"userName" URI:@"" parent:__parent skipNullProperty:NO];
    if(__userNameItemElement!=nil)
    {
        [__userNameItemElement setStringValue:self.userName];
    }
            
    DDXMLElement* __passwordItemElement=[__request writeElement:password type:[NSString class] name:@"password" URI:@"" parent:__parent skipNullProperty:NO];
    if(__passwordItemElement!=nil)
    {
        [__passwordItemElement setStringValue:self.password];
    }
            
    DDXMLElement* __CIDItemElement=[__request writeElement:CID type:[NSString class] name:@"CID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CIDItemElement!=nil)
    {
        [__CIDItemElement setStringValue:self.CID];
    }
            
    DDXMLElement* __ConfirmationIDItemElement=[__request writeElement:ConfirmationID type:[NSString class] name:@"ConfirmationID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ConfirmationIDItemElement!=nil)
    {
        [__ConfirmationIDItemElement setStringValue:self.ConfirmationID];
    }
            
    DDXMLElement* __RefferenceIDItemElement=[__request writeElement:RefferenceID type:[NSString class] name:@"RefferenceID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__RefferenceIDItemElement!=nil)
    {
        [__RefferenceIDItemElement setStringValue:self.RefferenceID];
    }


}
@end
