//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPCustomExcursionOperation.h"
#import "SAPExcursionPaxDetails.h"
#import "SAPExcursionCatagoryDetailsBody.h"
#import "SAPHelper.h"
#import "SAPCustomExcursionBookingDetailsBody.h"


@implementation SAPCustomExcursionBookingDetailsBody
@synthesize GiftIt;
@synthesize CustomExcursionItem;
@synthesize ExcursionBillingPaxDetails;
@synthesize ExcursionShippingPaxDetails;
@synthesize ExcursionSelection;

+ (SAPCustomExcursionBookingDetailsBody *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPCustomExcursionBookingDetailsBody* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"GiftIt"])
             {
                if([SAPHelper isValue:__node name:@"GiftIt"])
                {
                    self.GiftIt = [[__node stringValue] boolValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"CustomExcursionItem"])
             {
                if([SAPHelper isValue:__node name:@"CustomExcursionItem"])
                {
                    self.CustomExcursionItem = (SAPCustomExcursionOperation*)[__request createObject:__node type:[SAPCustomExcursionOperation class]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionBillingPaxDetails"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionBillingPaxDetails"])
                {
                    self.ExcursionBillingPaxDetails = (SAPExcursionPaxDetails*)[__request createObject:__node type:[SAPExcursionPaxDetails class]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionShippingPaxDetails"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionShippingPaxDetails"])
                {
                    self.ExcursionShippingPaxDetails = (SAPExcursionPaxDetails*)[__request createObject:__node type:[SAPExcursionPaxDetails class]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionSelection"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionSelection"])
                {
                    self.ExcursionSelection = (SAPExcursionCatagoryDetailsBody*)[__request createObject:__node type:[SAPExcursionCatagoryDetailsBody class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __GiftItItemElement=[__request writeElement:@"GiftIt" URI:@"" parent:__parent];
    [__GiftItItemElement setStringValue:[SAPHelper toBoolStringFromBool:self.GiftIt]];
            
    DDXMLElement* __CustomExcursionItemItemElement=[__request writeElement:CustomExcursionItem type:[SAPCustomExcursionOperation class] name:@"CustomExcursionItem" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomExcursionItemItemElement!=nil)
    {
        [self.CustomExcursionItem serialize:__CustomExcursionItemItemElement __request: __request];
    }
            
    DDXMLElement* __ExcursionBillingPaxDetailsItemElement=[__request writeElement:ExcursionBillingPaxDetails type:[SAPExcursionPaxDetails class] name:@"ExcursionBillingPaxDetails" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ExcursionBillingPaxDetailsItemElement!=nil)
    {
        [self.ExcursionBillingPaxDetails serialize:__ExcursionBillingPaxDetailsItemElement __request: __request];
    }
            
    DDXMLElement* __ExcursionShippingPaxDetailsItemElement=[__request writeElement:ExcursionShippingPaxDetails type:[SAPExcursionPaxDetails class] name:@"ExcursionShippingPaxDetails" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ExcursionShippingPaxDetailsItemElement!=nil)
    {
        [self.ExcursionShippingPaxDetails serialize:__ExcursionShippingPaxDetailsItemElement __request: __request];
    }
            
    DDXMLElement* __ExcursionSelectionItemElement=[__request writeElement:ExcursionSelection type:[SAPExcursionCatagoryDetailsBody class] name:@"ExcursionSelection" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ExcursionSelectionItemElement!=nil)
    {
        [self.ExcursionSelection serialize:__ExcursionSelectionItemElement __request: __request];
    }


}
@end
