//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPCustomExcursionOperation;
@class SAPExcursionPaxDetails;
@class SAPExcursionCatagoryDetailsBody;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPCustomExcursionBookingDetailsBody : NSObject <SAPISerializableObject>


@property (nonatomic,getter=getGiftIt) BOOL GiftIt;

@property (retain,nonatomic,getter=getCustomExcursionItem) SAPCustomExcursionOperation* CustomExcursionItem;

@property (retain,nonatomic,getter=getExcursionBillingPaxDetails) SAPExcursionPaxDetails* ExcursionBillingPaxDetails;

@property (retain,nonatomic,getter=getExcursionShippingPaxDetails) SAPExcursionPaxDetails* ExcursionShippingPaxDetails;

@property (retain,nonatomic,getter=getExcursionSelection) SAPExcursionCatagoryDetailsBody* ExcursionSelection;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPCustomExcursionBookingDetailsBody*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end