//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPCustomExcursionOperation.h"
#import "SAPHelper.h"
#import "SAPCustomExcursionOperationBody.h"


@implementation SAPCustomExcursionOperationBody
@synthesize CustomExcursionItem;

+ (SAPCustomExcursionOperationBody *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPCustomExcursionOperationBody* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"CustomExcursionItem"])
             {
                if([SAPHelper isValue:__node name:@"CustomExcursionItem"])
                {
                    self.CustomExcursionItem = (SAPCustomExcursionOperation*)[__request createObject:__node type:[SAPCustomExcursionOperation class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __CustomExcursionItemItemElement=[__request writeElement:CustomExcursionItem type:[SAPCustomExcursionOperation class] name:@"CustomExcursionItem" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomExcursionItemItemElement!=nil)
    {
        [self.CustomExcursionItem serialize:__CustomExcursionItemItemElement __request: __request];
    }


}
@end
