//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPOperationRealm.h"
#import "SAPCancellationResponseDetailsBody.h"
#import "SAPHelper.h"
#import "SAPCancelOperationResponse.h"


@implementation SAPCancelOperationResponse
@synthesize Header;
@synthesize Body;

+ (SAPCancelOperationResponse *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPCancelOperationResponse* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"Header"])
             {
                if([SAPHelper isValue:__node name:@"Header"])
                {
                    self.Header = (SAPOperationRealm*)[__request createObject:__node type:[SAPOperationRealm class]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Body"])
             {
                if([SAPHelper isValue:__node name:@"Body"])
                {
                    self.Body = (SAPCancellationResponseDetailsBody*)[__request createObject:__node type:[SAPCancellationResponseDetailsBody class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__parent skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [self.Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPCancellationResponseDetailsBody class] name:@"Body" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [self.Body serialize:__BodyItemElement __request: __request];
    }


}
@end
