//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPPromoDetails.h"
#import "SAPExcursionPricing.h"


@implementation SAPExcursionPricing
@synthesize TotalGrossRateInSellingCurrency;
@synthesize TotalTaxInSellingCurrency;
@synthesize TotalCommissionInSellingCurrency;
@synthesize TotalDiscountInSellingCurrency;
@synthesize PConvenienceFee;
@synthesize PServiceTax;
@synthesize PromoDetails;

+ (SAPExcursionPricing *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionPricing* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
        self.TotalGrossRateInSellingCurrency =[NSNumber numberWithInt:0];
        self.TotalTaxInSellingCurrency =[NSNumber numberWithInt:0];
        self.TotalCommissionInSellingCurrency =[NSNumber numberWithInt:0];
        self.TotalDiscountInSellingCurrency =[NSNumber numberWithInt:0];
        self.PConvenienceFee =[NSNumber numberWithInt:0];
        self.PServiceTax =[NSNumber numberWithInt:0];
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"TotalGrossRateInSellingCurrency"])
             {
                if([SAPHelper isValue:__node name:@"TotalGrossRateInSellingCurrency"])
                {
                    self.TotalGrossRateInSellingCurrency = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"TotalTaxInSellingCurrency"])
             {
                if([SAPHelper isValue:__node name:@"TotalTaxInSellingCurrency"])
                {
                    self.TotalTaxInSellingCurrency = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"TotalCommissionInSellingCurrency"])
             {
                if([SAPHelper isValue:__node name:@"TotalCommissionInSellingCurrency"])
                {
                    self.TotalCommissionInSellingCurrency = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"TotalDiscountInSellingCurrency"])
             {
                if([SAPHelper isValue:__node name:@"TotalDiscountInSellingCurrency"])
                {
                    self.TotalDiscountInSellingCurrency = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PConvenienceFee"])
             {
                if([SAPHelper isValue:__node name:@"PConvenienceFee"])
                {
                    self.PConvenienceFee = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PServiceTax"])
             {
                if([SAPHelper isValue:__node name:@"PServiceTax"])
                {
                    self.PServiceTax = [SAPHelper getNumber:[__node stringValue] isDecimal:FALSE];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PromoDetails"])
             {
                if([SAPHelper isValue:__node name:@"PromoDetails"])
                {
                    if(self.PromoDetails == nil)
                    {
                        self.PromoDetails =[NSMutableArray array];
                    }
                    [self.PromoDetails addObject:(SAPPromoDetails*)[__request createObject:__node type:[SAPPromoDetails class]]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __TotalGrossRateInSellingCurrencyItemElement=[__request writeElement:TotalGrossRateInSellingCurrency type:[NSNumber class] name:@"TotalGrossRateInSellingCurrency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TotalGrossRateInSellingCurrencyItemElement!=nil)
    {
        [__TotalGrossRateInSellingCurrencyItemElement setStringValue:[SAPHelper getStringFromNumber:self.TotalGrossRateInSellingCurrency]];
    }
            
    DDXMLElement* __TotalTaxInSellingCurrencyItemElement=[__request writeElement:TotalTaxInSellingCurrency type:[NSNumber class] name:@"TotalTaxInSellingCurrency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TotalTaxInSellingCurrencyItemElement!=nil)
    {
        [__TotalTaxInSellingCurrencyItemElement setStringValue:[SAPHelper getStringFromNumber:self.TotalTaxInSellingCurrency]];
    }
            
    DDXMLElement* __TotalCommissionInSellingCurrencyItemElement=[__request writeElement:TotalCommissionInSellingCurrency type:[NSNumber class] name:@"TotalCommissionInSellingCurrency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TotalCommissionInSellingCurrencyItemElement!=nil)
    {
        [__TotalCommissionInSellingCurrencyItemElement setStringValue:[SAPHelper getStringFromNumber:self.TotalCommissionInSellingCurrency]];
    }
            
    DDXMLElement* __TotalDiscountInSellingCurrencyItemElement=[__request writeElement:TotalDiscountInSellingCurrency type:[NSNumber class] name:@"TotalDiscountInSellingCurrency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TotalDiscountInSellingCurrencyItemElement!=nil)
    {
        [__TotalDiscountInSellingCurrencyItemElement setStringValue:[SAPHelper getStringFromNumber:self.TotalDiscountInSellingCurrency]];
    }
            
    DDXMLElement* __PConvenienceFeeItemElement=[__request writeElement:PConvenienceFee type:[NSNumber class] name:@"PConvenienceFee" URI:@"" parent:__parent skipNullProperty:NO];
    if(__PConvenienceFeeItemElement!=nil)
    {
        [__PConvenienceFeeItemElement setStringValue:[SAPHelper getStringFromNumber:self.PConvenienceFee]];
    }
            
    DDXMLElement* __PServiceTaxItemElement=[__request writeElement:PServiceTax type:[NSNumber class] name:@"PServiceTax" URI:@"" parent:__parent skipNullProperty:NO];
    if(__PServiceTaxItemElement!=nil)
    {
        [__PServiceTaxItemElement setStringValue:[SAPHelper getStringFromNumber:self.PServiceTax]];
    }
            
    if(self.PromoDetails!=nil)
    {
        for (SAPPromoDetails* __item in self.PromoDetails) {
            DDXMLElement* __PromoDetailsItemElement=[__request writeElement:PromoDetails type:[SAPPromoDetails class] name:@"PromoDetails" URI:@"" parent:__parent skipNullProperty:NO];
            if(__PromoDetailsItemElement!=nil)
            {
                [__item serialize:__PromoDetailsItemElement __request: __request];
            }
        }
    }


}
@end
