//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPExcursionCarPickupDetails.h"
#import "SAPHelper.h"
#import "SAPExcursionPaxDetails.h"


@implementation SAPExcursionPaxDetails
@synthesize LeadPax_First_Name;
@synthesize LeadPax_Middle_Name;
@synthesize LeadPax_Last_Name;
@synthesize DateOfBirth;
@synthesize Address1;
@synthesize Address2;
@synthesize City;
@synthesize State;
@synthesize Country;
@synthesize Zip;
@synthesize MobileNumber;
@synthesize EmailId;
@synthesize AddonsIncluded;
@synthesize PromotionCode;
@synthesize ExcursionCarPickupDetails;

+ (SAPExcursionPaxDetails *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionPaxDetails* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"LeadPax_First_Name"])
             {
                if([SAPHelper isValue:__node name:@"LeadPax_First_Name"])
                {
                    self.LeadPax_First_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"LeadPax_Middle_Name"])
             {
                if([SAPHelper isValue:__node name:@"LeadPax_Middle_Name"])
                {
                    self.LeadPax_Middle_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"LeadPax_Last_Name"])
             {
                if([SAPHelper isValue:__node name:@"LeadPax_Last_Name"])
                {
                    self.LeadPax_Last_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"DateOfBirth"])
             {
                if([SAPHelper isValue:__node name:@"DateOfBirth"])
                {
                    self.DateOfBirth = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Address1"])
             {
                if([SAPHelper isValue:__node name:@"Address1"])
                {
                    self.Address1 = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Address2"])
             {
                if([SAPHelper isValue:__node name:@"Address2"])
                {
                    self.Address2 = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"City"])
             {
                if([SAPHelper isValue:__node name:@"City"])
                {
                    self.City = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"State"])
             {
                if([SAPHelper isValue:__node name:@"State"])
                {
                    self.State = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Country"])
             {
                if([SAPHelper isValue:__node name:@"Country"])
                {
                    self.Country = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Zip"])
             {
                if([SAPHelper isValue:__node name:@"Zip"])
                {
                    self.Zip = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"MobileNumber"])
             {
                if([SAPHelper isValue:__node name:@"MobileNumber"])
                {
                    self.MobileNumber = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"EmailId"])
             {
                if([SAPHelper isValue:__node name:@"EmailId"])
                {
                    self.EmailId = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"AddonsIncluded"])
             {
                if([SAPHelper isValue:__node name:@"AddonsIncluded"])
                {
                    self.AddonsIncluded = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PromotionCode"])
             {
                if([SAPHelper isValue:__node name:@"PromotionCode"])
                {
                    self.PromotionCode = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionCarPickupDetails"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionCarPickupDetails"])
                {
                    self.ExcursionCarPickupDetails = (SAPExcursionCarPickupDetails*)[__request createObject:__node type:[SAPExcursionCarPickupDetails class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __LeadPax_First_NameItemElement=[__request writeElement:LeadPax_First_Name type:[NSString class] name:@"LeadPax_First_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__LeadPax_First_NameItemElement!=nil)
    {
        [__LeadPax_First_NameItemElement setStringValue:self.LeadPax_First_Name];
    }
            
    DDXMLElement* __LeadPax_Middle_NameItemElement=[__request writeElement:LeadPax_Middle_Name type:[NSString class] name:@"LeadPax_Middle_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__LeadPax_Middle_NameItemElement!=nil)
    {
        [__LeadPax_Middle_NameItemElement setStringValue:self.LeadPax_Middle_Name];
    }
            
    DDXMLElement* __LeadPax_Last_NameItemElement=[__request writeElement:LeadPax_Last_Name type:[NSString class] name:@"LeadPax_Last_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__LeadPax_Last_NameItemElement!=nil)
    {
        [__LeadPax_Last_NameItemElement setStringValue:self.LeadPax_Last_Name];
    }
            
    DDXMLElement* __DateOfBirthItemElement=[__request writeElement:DateOfBirth type:[NSString class] name:@"DateOfBirth" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DateOfBirthItemElement!=nil)
    {
        [__DateOfBirthItemElement setStringValue:self.DateOfBirth];
    }
            
    DDXMLElement* __Address1ItemElement=[__request writeElement:Address1 type:[NSString class] name:@"Address1" URI:@"" parent:__parent skipNullProperty:NO];
    if(__Address1ItemElement!=nil)
    {
        [__Address1ItemElement setStringValue:self.Address1];
    }
            
    DDXMLElement* __Address2ItemElement=[__request writeElement:Address2 type:[NSString class] name:@"Address2" URI:@"" parent:__parent skipNullProperty:NO];
    if(__Address2ItemElement!=nil)
    {
        [__Address2ItemElement setStringValue:self.Address2];
    }
            
    DDXMLElement* __CityItemElement=[__request writeElement:City type:[NSString class] name:@"City" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CityItemElement!=nil)
    {
        [__CityItemElement setStringValue:self.City];
    }
            
    DDXMLElement* __StateItemElement=[__request writeElement:State type:[NSString class] name:@"State" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StateItemElement!=nil)
    {
        [__StateItemElement setStringValue:self.State];
    }
            
    DDXMLElement* __CountryItemElement=[__request writeElement:Country type:[NSString class] name:@"Country" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CountryItemElement!=nil)
    {
        [__CountryItemElement setStringValue:self.Country];
    }
            
    DDXMLElement* __ZipItemElement=[__request writeElement:Zip type:[NSString class] name:@"Zip" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ZipItemElement!=nil)
    {
        [__ZipItemElement setStringValue:self.Zip];
    }
            
    DDXMLElement* __MobileNumberItemElement=[__request writeElement:MobileNumber type:[NSString class] name:@"MobileNumber" URI:@"" parent:__parent skipNullProperty:NO];
    if(__MobileNumberItemElement!=nil)
    {
        [__MobileNumberItemElement setStringValue:self.MobileNumber];
    }
            
    DDXMLElement* __EmailIdItemElement=[__request writeElement:EmailId type:[NSString class] name:@"EmailId" URI:@"" parent:__parent skipNullProperty:NO];
    if(__EmailIdItemElement!=nil)
    {
        [__EmailIdItemElement setStringValue:self.EmailId];
    }
            
    DDXMLElement* __AddonsIncludedItemElement=[__request writeElement:AddonsIncluded type:[NSString class] name:@"AddonsIncluded" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AddonsIncludedItemElement!=nil)
    {
        [__AddonsIncludedItemElement setStringValue:self.AddonsIncluded];
    }
            
    DDXMLElement* __PromotionCodeItemElement=[__request writeElement:PromotionCode type:[NSString class] name:@"PromotionCode" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PromotionCodeItemElement!=nil)
    {
        [__PromotionCodeItemElement setStringValue:self.PromotionCode];
    }
            
    DDXMLElement* __ExcursionCarPickupDetailsItemElement=[__request writeElement:ExcursionCarPickupDetails type:[SAPExcursionCarPickupDetails class] name:@"ExcursionCarPickupDetails" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ExcursionCarPickupDetailsItemElement!=nil)
    {
        [self.ExcursionCarPickupDetails serialize:__ExcursionCarPickupDetailsItemElement __request: __request];
    }


}
@end
