//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPExcursionCatagoryDetails;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPExcursionCatagoryDetailsBody : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getExcursionCatagory) SAPExcursionCatagoryDetails* ExcursionCatagory;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPExcursionCatagoryDetailsBody*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end