//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPExcursionCatagoryDetails.h"
#import "SAPHelper.h"
#import "SAPExcursionCatagoryDetailsBody.h"


@implementation SAPExcursionCatagoryDetailsBody
@synthesize ExcursionCatagory;

+ (SAPExcursionCatagoryDetailsBody *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionCatagoryDetailsBody* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"ExcursionCatagory"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionCatagory"])
                {
                    self.ExcursionCatagory = (SAPExcursionCatagoryDetails*)[__request createObject:__node type:[SAPExcursionCatagoryDetails class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __ExcursionCatagoryItemElement=[__request writeElement:ExcursionCatagory type:[SAPExcursionCatagoryDetails class] name:@"ExcursionCatagory" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ExcursionCatagoryItemElement!=nil)
    {
        [self.ExcursionCatagory serialize:__ExcursionCatagoryItemElement __request: __request];
    }


}
@end
