//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPExcursionCancellationPolicy.h"


@implementation SAPExcursionCancellationPolicy
@synthesize Hours;
@synthesize Charges;
@synthesize Policy;

+ (SAPExcursionCancellationPolicy *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionCancellationPolicy* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"Hours"])
             {
                if([SAPHelper isValue:__node name:@"Hours"])
                {
                    self.Hours = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Charges"])
             {
                if([SAPHelper isValue:__node name:@"Charges"])
                {
                    self.Charges = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Policy"])
             {
                if([SAPHelper isValue:__node name:@"Policy"])
                {
                    self.Policy = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __HoursItemElement=[__request writeElement:Hours type:[NSString class] name:@"Hours" URI:@"" parent:__parent skipNullProperty:YES];
    if(__HoursItemElement!=nil)
    {
        [__HoursItemElement setStringValue:self.Hours];
    }
            
    DDXMLElement* __ChargesItemElement=[__request writeElement:Charges type:[NSString class] name:@"Charges" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ChargesItemElement!=nil)
    {
        [__ChargesItemElement setStringValue:self.Charges];
    }
            
    DDXMLElement* __PolicyItemElement=[__request writeElement:Policy type:[NSString class] name:@"Policy" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PolicyItemElement!=nil)
    {
        [__PolicyItemElement setStringValue:self.Policy];
    }


}
@end
