//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "SAPAuthenticateOperationResponse.h"
#import "SAPAuthenticationRealm.h"
#import "SAPAuthenticateOperationBody.h"
#import "SAPSearchOperationResponse.h"
#import "SAPOperationRealm.h"
#import "SAPQueryExcursionOperationBody.h"
#import "SAPReportOperationResponse.h"
#import "SAPReportRequestOperationBody.h"
#import "SAPBookingOperationResponse.h"
#import "SAPExcursionConfirmBookingDetailsBody.h"
#import "SAPCancelOperationResponse.h"
#import "SAPCancellationDetailsBody.h"
#import "SAPSearchCustomExcursionOperationResponse.h"
#import "SAPCustomExcursionOperationBody.h"
#import "SAPBookCustomExcursionOperationResponse.h"
#import "SAPCustomExcursionBookingDetailsBody.h"
#import "SAPBookingStatusOperationResponse.h"
#import "SAPBookingStatusOperationBody.h"
#import "DDXML.h"

#import "SAPRequestResultHandler.h"

@interface SAPexcursionSOAPSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;
@property BOOL EnableLogging;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createAuthenticateOperationPORTRequest:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPAuthenticateOperationResponse*) AuthenticateOperationPORT:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) AuthenticateOperationPORTAsync:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) AuthenticateOperationPORTAsync:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) AuthenticateOperationPORTAsyncWithBlock:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createSearchOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPSearchOperationResponse*) SearchOperationPORT:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) SearchOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) SearchOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) SearchOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createGetReportOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPReportOperationResponse*) GetReportOperationPORT:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) GetReportOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) GetReportOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) GetReportOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createBookingOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPBookingOperationResponse*) BookingOperationPORT:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) BookingOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) BookingOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) BookingOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createCancelOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPCancelOperationResponse*) CancelOperationPORT:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) CancelOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) CancelOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) CancelOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createSearchCustomExcursionOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPSearchCustomExcursionOperationResponse*) SearchCustomExcursionOperationPORT:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) SearchCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) SearchCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) SearchCustomExcursionOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createBookCustomExcursionOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPBookCustomExcursionOperationResponse*) BookCustomExcursionOperationPORT:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) BookCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) BookCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) BookCustomExcursionOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __handler:(void(^) (id)) __handler;
-(NSMutableURLRequest*) createBookingStatusOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __request:(SAPRequestResultHandler*) __request;
-(SAPBookingStatusOperationResponse*) BookingStatusOperationPORT:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) BookingStatusOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) BookingStatusOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) BookingStatusOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __handler:(void(^) (id)) __handler;
-(NSString*) QueryCreditStatusOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) QueryCreditStatusOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) QueryCreditStatusOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) QueryCreditStatusOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) ReserveBookingOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) ReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) ReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) ReserveBookingOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) SearchAddonsOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) SearchAddonsOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) SearchAddonsOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) SearchAddonsOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) RepricingOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) RepricingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) RepricingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) RepricingOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) SearchServicesOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) SearchServicesOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) SearchServicesOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) SearchServicesOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) CityAndAirportListOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) CityAndAirportListOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) CityAndAirportListOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) CityAndAirportListOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) FlightTimeServiceOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) FlightTimeServiceOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) FlightTimeServiceOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) FlightTimeServiceOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(NSString*) ServicesReserveBookingOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error ;
-(SAPRequestResultHandler*) ServicesReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler;
-(SAPRequestResultHandler*) ServicesReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target;
-(SAPRequestResultHandler*) ServicesReserveBookingOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler;
-(SAPRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(SAPRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(SAPRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(SAPRequestResultHandler*) requestMgr callback:(void (^)(SAPRequestResultHandler *)) callback;

@end
