//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPExcursionOperationResponse;
@class SAPOperationError;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPExcursionOperationResponseBody : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getExcursionItemResponse) SAPExcursionOperationResponse* ExcursionItemResponse;

@property (retain,nonatomic,getter=getStatusCode) NSString* StatusCode;

@property (retain,nonatomic,getter=getStatusText) NSString* StatusText;

@property (retain,nonatomic,getter=getError) SAPOperationError* Error;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPExcursionOperationResponseBody*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end
