//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPHelper;
@class SAPPromoDetails;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPExcursionPricing : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getTotalGrossRateInSellingCurrency) NSNumber* TotalGrossRateInSellingCurrency;

@property (retain,nonatomic,getter=getTotalTaxInSellingCurrency) NSNumber* TotalTaxInSellingCurrency;

@property (retain,nonatomic,getter=getTotalCommissionInSellingCurrency) NSNumber* TotalCommissionInSellingCurrency;

@property (retain,nonatomic,getter=getTotalDiscountInSellingCurrency) NSNumber* TotalDiscountInSellingCurrency;

@property (retain,nonatomic,getter=getPConvenienceFee) NSNumber* PConvenienceFee;

@property (retain,nonatomic,getter=getPServiceTax) NSNumber* PServiceTax;

@property (retain,nonatomic,getter=getPromoDetails) NSMutableArray* PromoDetails;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPExcursionPricing*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end