//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPMiscellaneousCategoryInfo;
@class SAPExcursionTermsAndConditions;
@class SAPExcursionCancellationPolicy;
@class SAPExcursionVarriationDetails;
@class SAPExcursionPricing;
@class SAPAdditionalInformation;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPExcursionCatagoryDetails : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getSource_ID) NSString* Source_ID;

@property (retain,nonatomic,getter=getEvent_ID) NSString* Event_ID;

@property (retain,nonatomic,getter=getResource_ID) NSString* Resource_ID;

@property (retain,nonatomic,getter=getSource_ref_ID) NSString* Source_ref_ID;

@property (retain,nonatomic,getter=getCatagoryName) NSString* CatagoryName;

@property (retain,nonatomic,getter=getCatagoryDescription) NSString* CatagoryDescription;

@property (retain,nonatomic,getter=getIsRecommended) NSString* IsRecommended;

@property (retain,nonatomic,getter=getOfPassType) NSString* OfPassType;

@property (retain,nonatomic,getter=getCategoryUID) NSString* CategoryUID;

@property (retain,nonatomic,getter=getCategoryType) NSString* CategoryType;

@property (retain,nonatomic,getter=getServiceType) NSString* ServiceType;

@property (retain,nonatomic,getter=getMergedTypeCategory) NSString* MergedTypeCategory;

@property (retain,nonatomic,getter=getMiscellaneousCategoryInfo) NSMutableArray* MiscellaneousCategoryInfo;

@property (retain,nonatomic,getter=getExcursionTermsAndConditions) NSMutableArray* ExcursionTermsAndConditions;

@property (retain,nonatomic,getter=getExcursionCancellationPolicy) NSMutableArray* ExcursionCancellationPolicy;

@property (retain,nonatomic,getter=getExcursionVarriations) NSMutableArray* ExcursionVarriations;

@property (retain,nonatomic,getter=getExcursionCatagoryPricing) NSMutableArray* ExcursionCatagoryPricing;

@property (retain,nonatomic,getter=getAdditionalInformation) NSMutableArray* AdditionalInformation;

@property (retain,nonatomic,getter=getSelectedAdditionalInformation) NSString* selectedAdditionalInformation;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPExcursionCatagoryDetails*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end