//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPexcursionSOAPSoapBinding.h"
#import "SAPHelper.h"

@implementation SAPexcursionSOAPSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;
@synthesize EnableLogging;

- (id) init {
    if(self = [super init])
    {
        self.Url=@"http://demo.esselworld.in/excursionWSV3/services/excursionSOAP";
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(SAPRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(SAPRequestResultHandler*) CreateRequestResultHandler
{
    SAPRequestResultHandler* handler= [[SAPRequestResultHandler alloc]init:SOAPVERSION_11];
    handler.EnableLogging = EnableLogging;
    return handler;
}

-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(SAPRequestResultHandler*) __request
{
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    [__request prepareRequest:__requestObj];

    [__requestObj addValue: [NSString stringWithFormat:@"\"%@\"", __soapAction] forHTTPHeaderField:@"SOAPAction"];

    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];


    return __requestObj;
}


-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(SAPRequestResultHandler*) requestMgr callback:(void (^)(SAPRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createAuthenticateOperationPORTRequest:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"AuthenticateOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPAuthenticationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPAuthenticateOperationBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"AuthenticatOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) AuthenticateOperationPORTAsync:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createAuthenticateOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"AuthenticateOperationResponse"];
        __res= (SAPAuthenticateOperationResponse*)[__request createObject:__result type:[SAPAuthenticateOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) AuthenticateOperationPORTAsync:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createAuthenticateOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"AuthenticateOperationResponse"];
        [__target onSuccess:(SAPAuthenticateOperationResponse*)[__request createObject:__result type:[SAPAuthenticateOperationResponse class]] methodName:@"AuthenticateOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) AuthenticateOperationPORTAsyncWithBlock:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createAuthenticateOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"AuthenticateOperationResponse"];
        __res= (SAPAuthenticateOperationResponse*)[__request createObject:__result type:[SAPAuthenticateOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPAuthenticateOperationResponse*) AuthenticateOperationPORT:(SAPAuthenticationRealm*) Header Body:(SAPAuthenticateOperationBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createAuthenticateOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"AuthenticateOperationResponse"];
    return (SAPAuthenticateOperationResponse*)[__request createObject:__result type:[SAPAuthenticateOperationResponse class]];
}
-(NSMutableURLRequest*) createSearchOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"SearchOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPQueryExcursionOperationBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"SearchOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) SearchOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchOperationResponse"];
        __res= (SAPSearchOperationResponse*)[__request createObject:__result type:[SAPSearchOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) SearchOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchOperationResponse"];
        [__target onSuccess:(SAPSearchOperationResponse*)[__request createObject:__result type:[SAPSearchOperationResponse class]] methodName:@"SearchOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) SearchOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchOperationResponse"];
        __res= (SAPSearchOperationResponse*)[__request createObject:__result type:[SAPSearchOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPSearchOperationResponse*) SearchOperationPORT:(SAPOperationRealm*) Header Body:(SAPQueryExcursionOperationBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchOperationResponse"];
    return (SAPSearchOperationResponse*)[__request createObject:__result type:[SAPSearchOperationResponse class]];
}
-(NSMutableURLRequest*) createGetReportOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"ReportRequestOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPReportRequestOperationBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"GetReportOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) GetReportOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createGetReportOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"ReportOperationResponse"];
        __res= (SAPReportOperationResponse*)[__request createObject:__result type:[SAPReportOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) GetReportOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createGetReportOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"ReportOperationResponse"];
        [__target onSuccess:(SAPReportOperationResponse*)[__request createObject:__result type:[SAPReportOperationResponse class]] methodName:@"GetReportOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) GetReportOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createGetReportOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"ReportOperationResponse"];
        __res= (SAPReportOperationResponse*)[__request createObject:__result type:[SAPReportOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPReportOperationResponse*) GetReportOperationPORT:(SAPOperationRealm*) Header Body:(SAPReportRequestOperationBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createGetReportOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"ReportOperationResponse"];
    return (SAPReportOperationResponse*)[__request createObject:__result type:[SAPReportOperationResponse class]];
}
-(NSMutableURLRequest*) createBookingOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"BookingOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPExcursionConfirmBookingDetailsBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"BookingOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) BookingOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingOperationResponse"];
        __res= (SAPBookingOperationResponse*)[__request createObject:__result type:[SAPBookingOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) BookingOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingOperationResponse"];
        [__target onSuccess:(SAPBookingOperationResponse*)[__request createObject:__result type:[SAPBookingOperationResponse class]] methodName:@"BookingOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) BookingOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingOperationResponse"];
        __res= (SAPBookingOperationResponse*)[__request createObject:__result type:[SAPBookingOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPBookingOperationResponse*) BookingOperationPORT:(SAPOperationRealm*) Header Body:(SAPExcursionConfirmBookingDetailsBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingOperationResponse"];
    return (SAPBookingOperationResponse*)[__request createObject:__result type:[SAPBookingOperationResponse class]];
}
-(NSMutableURLRequest*) createCancelOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"CancelOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPCancellationDetailsBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"CancelOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) CancelOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createCancelOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"CancelOperationResponse"];
        __res= (SAPCancelOperationResponse*)[__request createObject:__result type:[SAPCancelOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) CancelOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createCancelOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"CancelOperationResponse"];
        [__target onSuccess:(SAPCancelOperationResponse*)[__request createObject:__result type:[SAPCancelOperationResponse class]] methodName:@"CancelOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) CancelOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createCancelOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"CancelOperationResponse"];
        __res= (SAPCancelOperationResponse*)[__request createObject:__result type:[SAPCancelOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPCancelOperationResponse*) CancelOperationPORT:(SAPOperationRealm*) Header Body:(SAPCancellationDetailsBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createCancelOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"CancelOperationResponse"];
    return (SAPCancelOperationResponse*)[__request createObject:__result type:[SAPCancelOperationResponse class]];
}
-(NSMutableURLRequest*) createSearchCustomExcursionOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"SearchCustomExcursionOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPCustomExcursionOperationBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"SearchCustomExcursionOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) SearchCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchCustomExcursionOperationResponse"];
        __res= (SAPSearchCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPSearchCustomExcursionOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) SearchCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchCustomExcursionOperationResponse"];
        [__target onSuccess:(SAPSearchCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPSearchCustomExcursionOperationResponse class]] methodName:@"SearchCustomExcursionOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) SearchCustomExcursionOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchCustomExcursionOperationResponse"];
        __res= (SAPSearchCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPSearchCustomExcursionOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPSearchCustomExcursionOperationResponse*) SearchCustomExcursionOperationPORT:(SAPOperationRealm*) Header Body:(SAPCustomExcursionOperationBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createSearchCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"SearchCustomExcursionOperationResponse"];
    return (SAPSearchCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPSearchCustomExcursionOperationResponse class]];
}
-(NSMutableURLRequest*) createBookCustomExcursionOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"BookCustomExcursionOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPCustomExcursionBookingDetailsBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"BookCustomExcursionOperation"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) BookCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookCustomExcursionOperationResponse"];
        __res= (SAPBookCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPBookCustomExcursionOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) BookCustomExcursionOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookCustomExcursionOperationResponse"];
        [__target onSuccess:(SAPBookCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPBookCustomExcursionOperationResponse class]] methodName:@"BookCustomExcursionOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) BookCustomExcursionOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookCustomExcursionOperationResponse"];
        __res= (SAPBookCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPBookCustomExcursionOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPBookCustomExcursionOperationResponse*) BookCustomExcursionOperationPORT:(SAPOperationRealm*) Header Body:(SAPCustomExcursionBookingDetailsBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookCustomExcursionOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookCustomExcursionOperationResponse"];
    return (SAPBookCustomExcursionOperationResponse*)[__request createObject:__result type:[SAPBookCustomExcursionOperationResponse class]];
}
-(NSMutableURLRequest*) createBookingStatusOperationPORTRequest:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __request:(SAPRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"BookingStatusOperation" URI:@"http://excursion.ws.com/Excursion/" parent:__request.Body];
    [self addAdornments:__methodElement];
            
    DDXMLElement* __HeaderItemElement=[__request writeElement:Header type:[SAPOperationRealm class] name:@"Header" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__HeaderItemElement!=nil)
    {
        [Header serialize:__HeaderItemElement __request: __request];
    }
            
    DDXMLElement* __BodyItemElement=[__request writeElement:Body type:[SAPBookingStatusOperationBody class] name:@"Body" URI:@"" parent:__methodElement skipNullProperty:NO];
    if(__BodyItemElement!=nil)
    {
        [Body serialize:__BodyItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@"BookingStatusOperationPORT"  __request:__request];
    return __requestObj;
}
    
-(SAPRequestResultHandler*) BookingStatusOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __target:(id) __target __handler:(SEL) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingStatusOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingStatusOperationResponse"];
        __res= (SAPBookingStatusOperationResponse*)[__request createObject:__result type:[SAPBookingStatusOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(SAPRequestResultHandler*) BookingStatusOperationPORTAsync:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingStatusOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingStatusOperationResponse"];
        [__target onSuccess:(SAPBookingStatusOperationResponse*)[__request createObject:__result type:[SAPBookingStatusOperationResponse class]] methodName:@"BookingStatusOperationPORT"];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}
-(SAPRequestResultHandler*) BookingStatusOperationPORTAsyncWithBlock:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __handler:(void(^) (id)) __handler
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingStatusOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(SAPRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingStatusOperationResponse"];
        __res= (SAPBookingStatusOperationResponse*)[__request createObject:__result type:[SAPBookingStatusOperationResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    __handler(__res);
    }];
    return __request;
    }

-(SAPBookingStatusOperationResponse*) BookingStatusOperationPORT:(SAPOperationRealm*) Header Body:(SAPBookingStatusOperationBody*) Body __error:(NSError**) __error
{
    SAPRequestResultHandler* __request = [self CreateRequestResultHandler];
    NSMutableURLRequest *__requestObj=[self createBookingStatusOperationPORTRequest:Header Body: Body __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[SAPHelper getResultElement:__request.OutputBody name:@"BookingStatusOperationResponse"];
    return (SAPBookingStatusOperationResponse*)[__request createObject:__result type:[SAPBookingStatusOperationResponse class]];
}
    
-(SAPRequestResultHandler*) QueryCreditStatusOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) QueryCreditStatusOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) QueryCreditStatusOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) QueryCreditStatusOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) ReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) ReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) ReserveBookingOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) ReserveBookingOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) SearchAddonsOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) SearchAddonsOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) SearchAddonsOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) SearchAddonsOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) RepricingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) RepricingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) RepricingOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) RepricingOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) SearchServicesOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) SearchServicesOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) SearchServicesOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) SearchServicesOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) CityAndAirportListOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) CityAndAirportListOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) CityAndAirportListOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) CityAndAirportListOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) FlightTimeServiceOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) FlightTimeServiceOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) FlightTimeServiceOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) FlightTimeServiceOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
    
-(SAPRequestResultHandler*) ServicesReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(SAPRequestResultHandler*) ServicesReserveBookingOperationPORTAsync:(NSString*) Header Body:(NSString*) Body __target:(id<SAPSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}
-(SAPRequestResultHandler*) ServicesReserveBookingOperationPORTAsyncWithBlock:(NSString*) Header Body:(NSString*) Body __handler:(void(^) (id)) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
    }

-(NSString*) ServicesReserveBookingOperationPORT:(NSString*) Header Body:(NSString*) Body __error:(NSError**) __error
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

@end
