//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPExcursionCarPickupDetails : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getLeadPax_First_Name) NSString* LeadPax_First_Name;

@property (retain,nonatomic,getter=getLeadPax_Middle_Name) NSString* LeadPax_Middle_Name;

@property (retain,nonatomic,getter=getLeadPax_Last_Name) NSString* LeadPax_Last_Name;

@property (retain,nonatomic,getter=getDateOfBirth) NSString* DateOfBirth;

@property (retain,nonatomic,getter=getAddress1) NSString* Address1;

@property (retain,nonatomic,getter=getAddress2) NSString* Address2;

@property (retain,nonatomic,getter=getCity) NSString* City;

@property (retain,nonatomic,getter=getState) NSString* State;

@property (retain,nonatomic,getter=getCountry) NSString* Country;

@property (retain,nonatomic,getter=getZip) NSString* Zip;

@property (retain,nonatomic,getter=getMobileNumber) NSString* MobileNumber;

@property (retain,nonatomic,getter=getEmailId) NSString* EmailId;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPExcursionCarPickupDetails*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end