//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPArrayOfExcursionCatagoryDetails.h"
#import "SAPHelper.h"
#import "SAPExcursionOperationResponse.h"


@implementation SAPExcursionOperationResponse
@synthesize ExcursionItem;

+ (SAPExcursionOperationResponse *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionOperationResponse* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"ExcursionItem"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionItem"])
                {
                    self.ExcursionItem = (SAPArrayOfExcursionCatagoryDetails*)[__request createObject:__node type:[SAPArrayOfExcursionCatagoryDetails class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __ExcursionItemItemElement=[__request writeElement:ExcursionItem type:[SAPArrayOfExcursionCatagoryDetails class] name:@"ExcursionItem" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ExcursionItemItemElement!=nil)
    {
        [self.ExcursionItem serialize:__ExcursionItemItemElement __request: __request];
    }


}
@end
