//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPExcursionPricing;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPExcursionVarriationDetails : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getVarriationCode) NSString* VarriationCode;

@property (retain,nonatomic,getter=getVarriationName) NSString* VarriationName;

@property (retain,nonatomic,getter=getVarriationDescription) NSString* VarriationDescription;

@property (retain,nonatomic,getter=getVarriationEventId) NSString* VarriationEventId;

@property (retain,nonatomic,getter=getVarriationEventTypeId) NSString* VarriationEventTypeId;

@property (retain,nonatomic,getter=getVarriationEventSectionId) NSString* VarriationEventSectionId;

@property (retain,nonatomic,getter=getVarriationConvenienceFee) NSString* VarriationConvenienceFee;

@property (retain,nonatomic,getter=getVarriationConvenienceFeeFlat) NSString* VarriationConvenienceFeeFlat;

@property (retain,nonatomic,getter=getVarriationPaxType) NSString* VarriationPaxType;

@property (retain,nonatomic,getter=getVarriationPaxCount) NSString* VarriationPaxCount;

@property (retain,nonatomic,getter=getExcursionVarriationPricing) NSMutableArray* ExcursionVarriationPricing;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPExcursionVarriationDetails*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end