//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPExcursionPricing.h"
#import "SAPHelper.h"
#import "SAPExcursionVarriationDetails.h"


@implementation SAPExcursionVarriationDetails
@synthesize VarriationCode;
@synthesize VarriationName;
@synthesize VarriationDescription;
@synthesize VarriationEventId;
@synthesize VarriationEventTypeId;
@synthesize VarriationEventSectionId;
@synthesize VarriationConvenienceFee;
@synthesize VarriationConvenienceFeeFlat;
@synthesize VarriationPaxType;
@synthesize VarriationPaxCount;
@synthesize ExcursionVarriationPricing;

+ (SAPExcursionVarriationDetails *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionVarriationDetails* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"VarriationCode"])
             {
                if([SAPHelper isValue:__node name:@"VarriationCode"])
                {
                    self.VarriationCode = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationName"])
             {
                if([SAPHelper isValue:__node name:@"VarriationName"])
                {
                    self.VarriationName = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationDescription"])
             {
                if([SAPHelper isValue:__node name:@"VarriationDescription"])
                {
                    self.VarriationDescription = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationEventId"])
             {
                if([SAPHelper isValue:__node name:@"VarriationEventId"])
                {
                    self.VarriationEventId = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationEventTypeId"])
             {
                if([SAPHelper isValue:__node name:@"VarriationEventTypeId"])
                {
                    self.VarriationEventTypeId = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationEventSectionId"])
             {
                if([SAPHelper isValue:__node name:@"VarriationEventSectionId"])
                {
                    self.VarriationEventSectionId = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationConvenienceFee"])
             {
                if([SAPHelper isValue:__node name:@"VarriationConvenienceFee"])
                {
                    self.VarriationConvenienceFee = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationConvenienceFeeFlat"])
             {
                if([SAPHelper isValue:__node name:@"VarriationConvenienceFeeFlat"])
                {
                    self.VarriationConvenienceFeeFlat = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationPaxType"])
             {
                if([SAPHelper isValue:__node name:@"VarriationPaxType"])
                {
                    self.VarriationPaxType = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"VarriationPaxCount"])
             {
                if([SAPHelper isValue:__node name:@"VarriationPaxCount"])
                {
                    self.VarriationPaxCount = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionVarriationPricing"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionVarriationPricing"])
                {
                    if(self.ExcursionVarriationPricing == nil)
                    {
                        self.ExcursionVarriationPricing =[NSMutableArray array];
                    }
                    [self.ExcursionVarriationPricing addObject:(SAPExcursionPricing*)[__request createObject:__node type:[SAPExcursionPricing class]]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __VarriationCodeItemElement=[__request writeElement:VarriationCode type:[NSString class] name:@"VarriationCode" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationCodeItemElement!=nil)
    {
        [__VarriationCodeItemElement setStringValue:self.VarriationCode];
    }
            
    DDXMLElement* __VarriationNameItemElement=[__request writeElement:VarriationName type:[NSString class] name:@"VarriationName" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationNameItemElement!=nil)
    {
        [__VarriationNameItemElement setStringValue:self.VarriationName];
    }
            
    DDXMLElement* __VarriationDescriptionItemElement=[__request writeElement:VarriationDescription type:[NSString class] name:@"VarriationDescription" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationDescriptionItemElement!=nil)
    {
        [__VarriationDescriptionItemElement setStringValue:self.VarriationDescription];
    }
            
    DDXMLElement* __VarriationEventIdItemElement=[__request writeElement:VarriationEventId type:[NSString class] name:@"VarriationEventId" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationEventIdItemElement!=nil)
    {
        [__VarriationEventIdItemElement setStringValue:self.VarriationEventId];
    }
            
    DDXMLElement* __VarriationEventTypeIdItemElement=[__request writeElement:VarriationEventTypeId type:[NSString class] name:@"VarriationEventTypeId" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationEventTypeIdItemElement!=nil)
    {
        [__VarriationEventTypeIdItemElement setStringValue:self.VarriationEventTypeId];
    }
            
    DDXMLElement* __VarriationEventSectionIdItemElement=[__request writeElement:VarriationEventSectionId type:[NSString class] name:@"VarriationEventSectionId" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationEventSectionIdItemElement!=nil)
    {
        [__VarriationEventSectionIdItemElement setStringValue:self.VarriationEventSectionId];
    }
            
    DDXMLElement* __VarriationConvenienceFeeItemElement=[__request writeElement:VarriationConvenienceFee type:[NSString class] name:@"VarriationConvenienceFee" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationConvenienceFeeItemElement!=nil)
    {
        [__VarriationConvenienceFeeItemElement setStringValue:self.VarriationConvenienceFee];
    }
            
    DDXMLElement* __VarriationConvenienceFeeFlatItemElement=[__request writeElement:VarriationConvenienceFeeFlat type:[NSString class] name:@"VarriationConvenienceFeeFlat" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationConvenienceFeeFlatItemElement!=nil)
    {
        [__VarriationConvenienceFeeFlatItemElement setStringValue:self.VarriationConvenienceFeeFlat];
    }
            
    DDXMLElement* __VarriationPaxTypeItemElement=[__request writeElement:VarriationPaxType type:[NSString class] name:@"VarriationPaxType" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationPaxTypeItemElement!=nil)
    {
        [__VarriationPaxTypeItemElement setStringValue:self.VarriationPaxType];
    }
            
    DDXMLElement* __VarriationPaxCountItemElement=[__request writeElement:VarriationPaxCount type:[NSString class] name:@"VarriationPaxCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VarriationPaxCountItemElement!=nil)
    {
        [__VarriationPaxCountItemElement setStringValue:self.VarriationPaxCount];
    }
            
    if(self.ExcursionVarriationPricing!=nil)
    {
        for (SAPExcursionPricing* __item in self.ExcursionVarriationPricing) {
            DDXMLElement* __ExcursionVarriationPricingItemElement=[__request writeElement:ExcursionVarriationPricing type:[SAPExcursionPricing class] name:@"ExcursionVarriationPricing" URI:@"" parent:__parent skipNullProperty:NO];
            if(__ExcursionVarriationPricingItemElement!=nil)
            {
                [__item serialize:__ExcursionVarriationPricingItemElement __request: __request];
            }
        }
    }


}
@end
