//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPMiscellaneousCategoryInfo.h"
#import "SAPExcursionTermsAndConditions.h"
#import "SAPExcursionCancellationPolicy.h"
#import "SAPExcursionVarriationDetails.h"
#import "SAPExcursionPricing.h"
#import "SAPAdditionalInformation.h"
#import "SAPHelper.h"
#import "SAPExcursionCatagoryDetails.h"


@implementation SAPExcursionCatagoryDetails
@synthesize Source_ID;
@synthesize Event_ID;
@synthesize Resource_ID;
@synthesize Source_ref_ID;
@synthesize CatagoryName;
@synthesize CatagoryDescription;
@synthesize IsRecommended;
@synthesize OfPassType;
@synthesize CategoryUID;
@synthesize CategoryType;
@synthesize ServiceType;
@synthesize MergedTypeCategory;
@synthesize MiscellaneousCategoryInfo;
@synthesize ExcursionTermsAndConditions;
@synthesize ExcursionCancellationPolicy;
@synthesize ExcursionVarriations;
@synthesize ExcursionCatagoryPricing;
@synthesize AdditionalInformation;
@synthesize selectedAdditionalInformation;

+ (SAPExcursionCatagoryDetails *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPExcursionCatagoryDetails* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"Source_ID"])
             {
                if([SAPHelper isValue:__node name:@"Source_ID"])
                {
                    self.Source_ID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Event_ID"])
             {
                if([SAPHelper isValue:__node name:@"Event_ID"])
                {
                    self.Event_ID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Resource_ID"])
             {
                if([SAPHelper isValue:__node name:@"Resource_ID"])
                {
                    self.Resource_ID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Source_ref_ID"])
             {
                if([SAPHelper isValue:__node name:@"Source_ref_ID"])
                {
                    self.Source_ref_ID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"CatagoryName"])
             {
                if([SAPHelper isValue:__node name:@"CatagoryName"])
                {
                    self.CatagoryName = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"CatagoryDescription"])
             {
                if([SAPHelper isValue:__node name:@"CatagoryDescription"])
                {
                    self.CatagoryDescription = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"IsRecommended"])
             {
                if([SAPHelper isValue:__node name:@"IsRecommended"])
                {
                    self.IsRecommended = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"OfPassType"])
             {
                if([SAPHelper isValue:__node name:@"OfPassType"])
                {
                    self.OfPassType = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"CategoryUID"])
             {
                if([SAPHelper isValue:__node name:@"CategoryUID"])
                {
                    self.CategoryUID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"CategoryType"])
             {
                if([SAPHelper isValue:__node name:@"CategoryType"])
                {
                    self.CategoryType = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ServiceType"])
             {
                if([SAPHelper isValue:__node name:@"ServiceType"])
                {
                    self.ServiceType = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"MergedTypeCategory"])
             {
                if([SAPHelper isValue:__node name:@"MergedTypeCategory"])
                {
                    self.MergedTypeCategory = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"MiscellaneousCategoryInfo"])
             {
                if([SAPHelper isValue:__node name:@"MiscellaneousCategoryInfo"])
                {
                    if(self.MiscellaneousCategoryInfo == nil)
                    {
                        self.MiscellaneousCategoryInfo =[NSMutableArray array];
                    }
                    [self.MiscellaneousCategoryInfo addObject:(SAPMiscellaneousCategoryInfo*)[__request createObject:__node type:[SAPMiscellaneousCategoryInfo class]]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionTermsAndConditions"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionTermsAndConditions"])
                {
                    if(self.ExcursionTermsAndConditions == nil)
                    {
                        self.ExcursionTermsAndConditions =[NSMutableArray array];
                    }
                    [self.ExcursionTermsAndConditions addObject:(SAPExcursionTermsAndConditions*)[__request createObject:__node type:[SAPExcursionTermsAndConditions class]]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionCancellationPolicy"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionCancellationPolicy"])
                {
                    if(self.ExcursionCancellationPolicy == nil)
                    {
                        self.ExcursionCancellationPolicy =[NSMutableArray array];
                    }
                    [self.ExcursionCancellationPolicy addObject:(SAPExcursionCancellationPolicy*)[__request createObject:__node type:[SAPExcursionCancellationPolicy class]]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionVarriations"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionVarriations"])
                {
                    if(self.ExcursionVarriations == nil)
                    {
                        self.ExcursionVarriations =[NSMutableArray array];
                    }
                    [self.ExcursionVarriations addObject:(SAPExcursionVarriationDetails*)[__request createObject:__node type:[SAPExcursionVarriationDetails class]]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ExcursionCatagoryPricing"])
             {
                if([SAPHelper isValue:__node name:@"ExcursionCatagoryPricing"])
                {
                    if(self.ExcursionCatagoryPricing == nil)
                    {
                        self.ExcursionCatagoryPricing =[NSMutableArray array];
                    }
                    [self.ExcursionCatagoryPricing addObject:(SAPExcursionPricing*)[__request createObject:__node type:[SAPExcursionPricing class]]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"AdditionalInformation"])
             {
                if([SAPHelper isValue:__node name:@"AdditionalInformation"])
                {
                    if(self.AdditionalInformation == nil)
                    {
                        self.AdditionalInformation =[NSMutableArray array];
                    }
                    [self.AdditionalInformation addObject:(SAPAdditionalInformation*)[__request createObject:__node type:[SAPAdditionalInformation class]]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"selectedAdditionalInformation"])
             {
                if([SAPHelper isValue:__node name:@"selectedAdditionalInformation"])
                {
                    self.selectedAdditionalInformation = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __Source_IDItemElement=[__request writeElement:Source_ID type:[NSString class] name:@"Source_ID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__Source_IDItemElement!=nil)
    {
        [__Source_IDItemElement setStringValue:self.Source_ID];
    }
            
    DDXMLElement* __Event_IDItemElement=[__request writeElement:Event_ID type:[NSString class] name:@"Event_ID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__Event_IDItemElement!=nil)
    {
        [__Event_IDItemElement setStringValue:self.Event_ID];
    }
            
    DDXMLElement* __Resource_IDItemElement=[__request writeElement:Resource_ID type:[NSString class] name:@"Resource_ID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__Resource_IDItemElement!=nil)
    {
        [__Resource_IDItemElement setStringValue:self.Resource_ID];
    }
            
    DDXMLElement* __Source_ref_IDItemElement=[__request writeElement:Source_ref_ID type:[NSString class] name:@"Source_ref_ID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__Source_ref_IDItemElement!=nil)
    {
        [__Source_ref_IDItemElement setStringValue:self.Source_ref_ID];
    }
            
    DDXMLElement* __CatagoryNameItemElement=[__request writeElement:CatagoryName type:[NSString class] name:@"CatagoryName" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CatagoryNameItemElement!=nil)
    {
        [__CatagoryNameItemElement setStringValue:self.CatagoryName];
    }
            
    DDXMLElement* __CatagoryDescriptionItemElement=[__request writeElement:CatagoryDescription type:[NSString class] name:@"CatagoryDescription" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CatagoryDescriptionItemElement!=nil)
    {
        [__CatagoryDescriptionItemElement setStringValue:self.CatagoryDescription];
    }
            
    DDXMLElement* __IsRecommendedItemElement=[__request writeElement:IsRecommended type:[NSString class] name:@"IsRecommended" URI:@"" parent:__parent skipNullProperty:NO];
    if(__IsRecommendedItemElement!=nil)
    {
        [__IsRecommendedItemElement setStringValue:self.IsRecommended];
    }
            
    DDXMLElement* __OfPassTypeItemElement=[__request writeElement:OfPassType type:[NSString class] name:@"OfPassType" URI:@"" parent:__parent skipNullProperty:NO];
    if(__OfPassTypeItemElement!=nil)
    {
        [__OfPassTypeItemElement setStringValue:self.OfPassType];
    }
            
    DDXMLElement* __CategoryUIDItemElement=[__request writeElement:CategoryUID type:[NSString class] name:@"CategoryUID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CategoryUIDItemElement!=nil)
    {
        [__CategoryUIDItemElement setStringValue:self.CategoryUID];
    }
            
    DDXMLElement* __CategoryTypeItemElement=[__request writeElement:CategoryType type:[NSString class] name:@"CategoryType" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CategoryTypeItemElement!=nil)
    {
        [__CategoryTypeItemElement setStringValue:self.CategoryType];
    }
            
    DDXMLElement* __ServiceTypeItemElement=[__request writeElement:ServiceType type:[NSString class] name:@"ServiceType" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ServiceTypeItemElement!=nil)
    {
        [__ServiceTypeItemElement setStringValue:self.ServiceType];
    }
            
    DDXMLElement* __MergedTypeCategoryItemElement=[__request writeElement:MergedTypeCategory type:[NSString class] name:@"MergedTypeCategory" URI:@"" parent:__parent skipNullProperty:NO];
    if(__MergedTypeCategoryItemElement!=nil)
    {
        [__MergedTypeCategoryItemElement setStringValue:self.MergedTypeCategory];
    }
            
    if(self.MiscellaneousCategoryInfo!=nil)
    {
        for (SAPMiscellaneousCategoryInfo* __item in self.MiscellaneousCategoryInfo) {
            DDXMLElement* __MiscellaneousCategoryInfoItemElement=[__request writeElement:MiscellaneousCategoryInfo type:[SAPMiscellaneousCategoryInfo class] name:@"MiscellaneousCategoryInfo" URI:@"" parent:__parent skipNullProperty:NO];
            if(__MiscellaneousCategoryInfoItemElement!=nil)
            {
                [__item serialize:__MiscellaneousCategoryInfoItemElement __request: __request];
            }
        }
    }
            
    if(self.ExcursionTermsAndConditions!=nil)
    {
        for (SAPExcursionTermsAndConditions* __item in self.ExcursionTermsAndConditions) {
            DDXMLElement* __ExcursionTermsAndConditionsItemElement=[__request writeElement:ExcursionTermsAndConditions type:[SAPExcursionTermsAndConditions class] name:@"ExcursionTermsAndConditions" URI:@"" parent:__parent skipNullProperty:NO];
            if(__ExcursionTermsAndConditionsItemElement!=nil)
            {
                [__item serialize:__ExcursionTermsAndConditionsItemElement __request: __request];
            }
        }
    }
            
    if(self.ExcursionCancellationPolicy!=nil)
    {
        for (SAPExcursionCancellationPolicy* __item in self.ExcursionCancellationPolicy) {
            DDXMLElement* __ExcursionCancellationPolicyItemElement=[__request writeElement:ExcursionCancellationPolicy type:[SAPExcursionCancellationPolicy class] name:@"ExcursionCancellationPolicy" URI:@"" parent:__parent skipNullProperty:NO];
            if(__ExcursionCancellationPolicyItemElement!=nil)
            {
                [__item serialize:__ExcursionCancellationPolicyItemElement __request: __request];
            }
        }
    }
            
    if(self.ExcursionVarriations!=nil)
    {
        for (SAPExcursionVarriationDetails* __item in self.ExcursionVarriations) {
            DDXMLElement* __ExcursionVarriationsItemElement=[__request writeElement:ExcursionVarriations type:[SAPExcursionVarriationDetails class] name:@"ExcursionVarriations" URI:@"" parent:__parent skipNullProperty:NO];
            if(__ExcursionVarriationsItemElement!=nil)
            {
                [__item serialize:__ExcursionVarriationsItemElement __request: __request];
            }
        }
    }
            
    if(self.ExcursionCatagoryPricing!=nil)
    {
        for (SAPExcursionPricing* __item in self.ExcursionCatagoryPricing) {
            DDXMLElement* __ExcursionCatagoryPricingItemElement=[__request writeElement:ExcursionCatagoryPricing type:[SAPExcursionPricing class] name:@"ExcursionCatagoryPricing" URI:@"" parent:__parent skipNullProperty:NO];
            if(__ExcursionCatagoryPricingItemElement!=nil)
            {
                [__item serialize:__ExcursionCatagoryPricingItemElement __request: __request];
            }
        }
    }
            
    if(self.AdditionalInformation!=nil)
    {
        for (SAPAdditionalInformation* __item in self.AdditionalInformation) {
            DDXMLElement* __AdditionalInformationItemElement=[__request writeElement:AdditionalInformation type:[SAPAdditionalInformation class] name:@"AdditionalInformation" URI:@"" parent:__parent skipNullProperty:NO];
            if(__AdditionalInformationItemElement!=nil)
            {
                [__item serialize:__AdditionalInformationItemElement __request: __request];
            }
        }
    }
            
    DDXMLElement* __selectedAdditionalInformationItemElement=[__request writeElement:selectedAdditionalInformation type:[NSString class] name:@"selectedAdditionalInformation" URI:@"" parent:__parent skipNullProperty:YES];
    if(__selectedAdditionalInformationItemElement!=nil)
    {
        [__selectedAdditionalInformationItemElement setStringValue:self.selectedAdditionalInformation];
    }


}
@end
