//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPMiscellaneousCategoryInfo.h"


@implementation SAPMiscellaneousCategoryInfo
@synthesize Key;
@synthesize Value;

+ (SAPMiscellaneousCategoryInfo *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPMiscellaneousCategoryInfo* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"Key"])
             {
                if([SAPHelper isValue:__node name:@"Key"])
                {
                    self.Key = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"Value"])
             {
                if([SAPHelper isValue:__node name:@"Value"])
                {
                    self.Value = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __KeyItemElement=[__request writeElement:Key type:[NSString class] name:@"Key" URI:@"" parent:__parent skipNullProperty:YES];
    if(__KeyItemElement!=nil)
    {
        [__KeyItemElement setStringValue:self.Key];
    }
            
    DDXMLElement* __ValueItemElement=[__request writeElement:Value type:[NSString class] name:@"Value" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ValueItemElement!=nil)
    {
        [__ValueItemElement setStringValue:self.Value];
    }


}
@end
