//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPOperationError.h"


@implementation SAPOperationError
@synthesize ErrorCode;
@synthesize ErrorText;

+ (SAPOperationError *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPOperationError* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"ErrorCode"])
             {
                if([SAPHelper isValue:__node name:@"ErrorCode"])
                {
                    self.ErrorCode = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ErrorText"])
             {
                if([SAPHelper isValue:__node name:@"ErrorText"])
                {
                    self.ErrorText = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __ErrorCodeItemElement=[__request writeElement:ErrorCode type:[NSString class] name:@"ErrorCode" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ErrorCodeItemElement!=nil)
    {
        [__ErrorCodeItemElement setStringValue:self.ErrorCode];
    }
            
    DDXMLElement* __ErrorTextItemElement=[__request writeElement:ErrorText type:[NSString class] name:@"ErrorText" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ErrorTextItemElement!=nil)
    {
        [__ErrorTextItemElement setStringValue:self.ErrorText];
    }


}
@end
