//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPOperationRealm : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getSourceID) NSString* SourceID;

@property (retain,nonatomic,getter=getMessageID) NSString* MessageID;

@property (retain,nonatomic,getter=getMessageType) NSString* MessageType;

@property (retain,nonatomic,getter=getSessionID) NSString* SessionID;

@property (retain,nonatomic,getter=getTimeStamp) NSString* TimeStamp;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPOperationRealm*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end