//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPPromoDetails.h"


@implementation SAPPromoDetails
@synthesize PromocodeUsed;
@synthesize PromocodeDescription;

+ (SAPPromoDetails *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPPromoDetails* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"PromocodeUsed"])
             {
                if([SAPHelper isValue:__node name:@"PromocodeUsed"])
                {
                    self.PromocodeUsed = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PromocodeDescription"])
             {
                if([SAPHelper isValue:__node name:@"PromocodeDescription"])
                {
                    self.PromocodeDescription = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __PromocodeUsedItemElement=[__request writeElement:PromocodeUsed type:[NSString class] name:@"PromocodeUsed" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PromocodeUsedItemElement!=nil)
    {
        [__PromocodeUsedItemElement setStringValue:self.PromocodeUsed];
    }
            
    DDXMLElement* __PromocodeDescriptionItemElement=[__request writeElement:PromocodeDescription type:[NSString class] name:@"PromocodeDescription" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PromocodeDescriptionItemElement!=nil)
    {
        [__PromocodeDescriptionItemElement setStringValue:self.PromocodeDescription];
    }


}
@end
