//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPQueryExcursionOperation.h"
#import "SAPHelper.h"
#import "SAPQueryExcursionOperationBody.h"


@implementation SAPQueryExcursionOperationBody
@synthesize QueryExcursionItem;

+ (SAPQueryExcursionOperationBody *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPQueryExcursionOperationBody* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"QueryExcursionItem"])
             {
                if([SAPHelper isValue:__node name:@"QueryExcursionItem"])
                {
                    self.QueryExcursionItem = (SAPQueryExcursionOperation*)[__request createObject:__node type:[SAPQueryExcursionOperation class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __QueryExcursionItemItemElement=[__request writeElement:QueryExcursionItem type:[SAPQueryExcursionOperation class] name:@"QueryExcursionItem" URI:@"" parent:__parent skipNullProperty:NO];
    if(__QueryExcursionItemItemElement!=nil)
    {
        [self.QueryExcursionItem serialize:__QueryExcursionItemItemElement __request: __request];
    }


}
@end
