//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class SAPHelper;
#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPQueryExcursionOperation : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getAdults) NSNumber* Adults;

@property (retain,nonatomic,getter=getChildren) NSNumber* Children;

@property (retain,nonatomic,getter=getInfant) NSNumber* Infant;

@property (retain,nonatomic,getter=getSenior) NSNumber* Senior;

@property (retain,nonatomic,getter=getDateOFVisit) NSDate* DateOFVisit;

@property (retain,nonatomic,getter=getPassType) NSNumber* PassType;

@property (retain,nonatomic,getter=getServiceType) NSNumber* ServiceType;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPQueryExcursionOperation*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end