//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPArrayOfReportItemDetail.h"
#import "SAPHelper.h"
#import "SAPReportResponse.h"


@implementation SAPReportResponse
@synthesize ReportItem;

+ (SAPReportResponse *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPReportResponse* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"ReportItem"])
             {
                if([SAPHelper isValue:__node name:@"ReportItem"])
                {
                    self.ReportItem = (SAPArrayOfReportItemDetail*)[__request createObject:__node type:[SAPArrayOfReportItemDetail class]];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __ReportItemItemElement=[__request writeElement:ReportItem type:[SAPArrayOfReportItemDetail class] name:@"ReportItem" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ReportItemItemElement!=nil)
    {
        [self.ReportItem serialize:__ReportItemItemElement __request: __request];
    }


}
@end
