//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPReportQueryOperation.h"


@implementation SAPReportQueryOperation
@synthesize BookingFromDate;
@synthesize BookingToDate;
@synthesize BookingFromTime;
@synthesize BookingToTime;
@synthesize DepartureFromDate;
@synthesize DepartureToDate;
@synthesize DepartureFromTime;
@synthesize DepartureToTime;
@synthesize ReportType;
@synthesize AgencyId;

+ (SAPReportQueryOperation *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPReportQueryOperation* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"BookingFromDate"])
             {
                if([SAPHelper isValue:__node name:@"BookingFromDate"])
                {
                    self.BookingFromDate = [SAPHelper getDate:[__node stringValue]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"BookingToDate"])
             {
                if([SAPHelper isValue:__node name:@"BookingToDate"])
                {
                    self.BookingToDate = [SAPHelper getDate:[__node stringValue]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"BookingFromTime"])
             {
                if([SAPHelper isValue:__node name:@"BookingFromTime"])
                {
                    self.BookingFromTime = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"BookingToTime"])
             {
                if([SAPHelper isValue:__node name:@"BookingToTime"])
                {
                    self.BookingToTime = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"DepartureFromDate"])
             {
                if([SAPHelper isValue:__node name:@"DepartureFromDate"])
                {
                    self.DepartureFromDate = [SAPHelper getDate:[__node stringValue]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"DepartureToDate"])
             {
                if([SAPHelper isValue:__node name:@"DepartureToDate"])
                {
                    self.DepartureToDate = [SAPHelper getDate:[__node stringValue]];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"DepartureFromTime"])
             {
                if([SAPHelper isValue:__node name:@"DepartureFromTime"])
                {
                    self.DepartureFromTime = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"DepartureToTime"])
             {
                if([SAPHelper isValue:__node name:@"DepartureToTime"])
                {
                    self.DepartureToTime = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ReportType"])
             {
                if([SAPHelper isValue:__node name:@"ReportType"])
                {
                    self.ReportType = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"AgencyId"])
             {
                if([SAPHelper isValue:__node name:@"AgencyId"])
                {
                    self.AgencyId = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __BookingFromDateItemElement=[__request writeElement:BookingFromDate type:[NSDate class] name:@"BookingFromDate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__BookingFromDateItemElement!=nil)
    {
        [__BookingFromDateItemElement setStringValue:[SAPHelper getStringFromDate:self.BookingFromDate]];
    }
            
    DDXMLElement* __BookingToDateItemElement=[__request writeElement:BookingToDate type:[NSDate class] name:@"BookingToDate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__BookingToDateItemElement!=nil)
    {
        [__BookingToDateItemElement setStringValue:[SAPHelper getStringFromDate:self.BookingToDate]];
    }
            
    DDXMLElement* __BookingFromTimeItemElement=[__request writeElement:BookingFromTime type:[NSString class] name:@"BookingFromTime" URI:@"" parent:__parent skipNullProperty:YES];
    if(__BookingFromTimeItemElement!=nil)
    {
        [__BookingFromTimeItemElement setStringValue:self.BookingFromTime];
    }
            
    DDXMLElement* __BookingToTimeItemElement=[__request writeElement:BookingToTime type:[NSString class] name:@"BookingToTime" URI:@"" parent:__parent skipNullProperty:YES];
    if(__BookingToTimeItemElement!=nil)
    {
        [__BookingToTimeItemElement setStringValue:self.BookingToTime];
    }
            
    DDXMLElement* __DepartureFromDateItemElement=[__request writeElement:DepartureFromDate type:[NSDate class] name:@"DepartureFromDate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__DepartureFromDateItemElement!=nil)
    {
        [__DepartureFromDateItemElement setStringValue:[SAPHelper getStringFromDate:self.DepartureFromDate]];
    }
            
    DDXMLElement* __DepartureToDateItemElement=[__request writeElement:DepartureToDate type:[NSDate class] name:@"DepartureToDate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__DepartureToDateItemElement!=nil)
    {
        [__DepartureToDateItemElement setStringValue:[SAPHelper getStringFromDate:self.DepartureToDate]];
    }
            
    DDXMLElement* __DepartureFromTimeItemElement=[__request writeElement:DepartureFromTime type:[NSString class] name:@"DepartureFromTime" URI:@"" parent:__parent skipNullProperty:YES];
    if(__DepartureFromTimeItemElement!=nil)
    {
        [__DepartureFromTimeItemElement setStringValue:self.DepartureFromTime];
    }
            
    DDXMLElement* __DepartureToTimeItemElement=[__request writeElement:DepartureToTime type:[NSString class] name:@"DepartureToTime" URI:@"" parent:__parent skipNullProperty:YES];
    if(__DepartureToTimeItemElement!=nil)
    {
        [__DepartureToTimeItemElement setStringValue:self.DepartureToTime];
    }
            
    DDXMLElement* __ReportTypeItemElement=[__request writeElement:ReportType type:[NSString class] name:@"ReportType" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ReportTypeItemElement!=nil)
    {
        [__ReportTypeItemElement setStringValue:self.ReportType];
    }
            
    DDXMLElement* __AgencyIdItemElement=[__request writeElement:AgencyId type:[NSString class] name:@"AgencyId" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AgencyIdItemElement!=nil)
    {
        [__AgencyIdItemElement setStringValue:self.AgencyId];
    }


}
@end
