//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPReportQueryOperation : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getBookingFromDate) NSDate* BookingFromDate;

@property (retain,nonatomic,getter=getBookingToDate) NSDate* BookingToDate;

@property (retain,nonatomic,getter=getBookingFromTime) NSString* BookingFromTime;

@property (retain,nonatomic,getter=getBookingToTime) NSString* BookingToTime;

@property (retain,nonatomic,getter=getDepartureFromDate) NSDate* DepartureFromDate;

@property (retain,nonatomic,getter=getDepartureToDate) NSDate* DepartureToDate;

@property (retain,nonatomic,getter=getDepartureFromTime) NSString* DepartureFromTime;

@property (retain,nonatomic,getter=getDepartureToTime) NSString* DepartureToTime;

@property (retain,nonatomic,getter=getReportType) NSString* ReportType;

@property (retain,nonatomic,getter=getAgencyId) NSString* AgencyId;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPReportQueryOperation*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end