//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPHelper.h"
#import "SAPReportItemDetail.h"


@implementation SAPReportItemDetail
@synthesize SL_No;
@synthesize transaction_Date;
@synthesize booking_Time;
@synthesize invoiced_Date;
@synthesize date_Of_Visit;
@synthesize transaction_Type;
@synthesize agent_Name;
@synthesize PSA_Name;
@synthesize transaction_ID;
@synthesize galaxy_ID;
@synthesize destination;
@synthesize ticket_Type;
@synthesize status;
@synthesize package_Code;
@synthesize package_Name;
@synthesize customer_Name;
@synthesize customer_Address1;
@synthesize city;
@synthesize state;
@synthesize pin_Code;
@synthesize email;
@synthesize contact_Details;
@synthesize adults;
@synthesize children;
@synthesize infants;
@synthesize senior_Citizens;
@synthesize ticket_Cost;
@synthesize package_Cost;
@synthesize total_Cost;
@synthesize commission;
@synthesize serTax;
@synthesize TDS;
@synthesize total_Cost_To_Agent;
@synthesize promotion_Amount;
@synthesize net_Amount;
@synthesize cancellation_Penalty;
@synthesize refund_Amount;
@synthesize promo_Code;
@synthesize auto_Promo_code;
@synthesize gifted;
@synthesize gifted_To;
@synthesize PG_Name;
@synthesize payment_Ref_Id;
@synthesize order_Ref_Id;
@synthesize app_Booking;

+ (SAPReportItemDetail *)createWithXml:(DDXMLElement *)__node __request:(SAPRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    SAPReportItemDetail* obj = [[self alloc] init];
    [obj loadWithXml: __node __request:__request];
    return obj;
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (void) loadWithXml: (DDXMLElement*) __node __request:(SAPRequestResultHandler*) __request{
    DDXMLNode* node=__node;
    for(int i=0;i< node.childCount;i++)
    {
        DDXMLNode* node=[__node childAtIndex:i];
        if(node.kind==DDXMLElementKind)
        {
            DDXMLElement* __node=(DDXMLElement*)node;
             if([__node.localName isEqualToString:@"SL_No"])
             {
                if([SAPHelper isValue:__node name:@"SL_No"])
                {
                    self.SL_No = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"transaction_Date"])
             {
                if([SAPHelper isValue:__node name:@"transaction_Date"])
                {
                    self.transaction_Date = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"booking_Time"])
             {
                if([SAPHelper isValue:__node name:@"booking_Time"])
                {
                    self.booking_Time = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"invoiced_Date"])
             {
                if([SAPHelper isValue:__node name:@"invoiced_Date"])
                {
                    self.invoiced_Date = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"date_Of_Visit"])
             {
                if([SAPHelper isValue:__node name:@"date_Of_Visit"])
                {
                    self.date_Of_Visit = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"transaction_Type"])
             {
                if([SAPHelper isValue:__node name:@"transaction_Type"])
                {
                    self.transaction_Type = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"agent_Name"])
             {
                if([SAPHelper isValue:__node name:@"agent_Name"])
                {
                    self.agent_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PSA_Name"])
             {
                if([SAPHelper isValue:__node name:@"PSA_Name"])
                {
                    self.PSA_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"transaction_ID"])
             {
                if([SAPHelper isValue:__node name:@"transaction_ID"])
                {
                    self.transaction_ID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"galaxy_ID"])
             {
                if([SAPHelper isValue:__node name:@"galaxy_ID"])
                {
                    self.galaxy_ID = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"destination"])
             {
                if([SAPHelper isValue:__node name:@"destination"])
                {
                    self.destination = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ticket_Type"])
             {
                if([SAPHelper isValue:__node name:@"ticket_Type"])
                {
                    self.ticket_Type = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"status"])
             {
                if([SAPHelper isValue:__node name:@"status"])
                {
                    self.status = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"package_Code"])
             {
                if([SAPHelper isValue:__node name:@"package_Code"])
                {
                    self.package_Code = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"package_Name"])
             {
                if([SAPHelper isValue:__node name:@"package_Name"])
                {
                    self.package_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"customer_Name"])
             {
                if([SAPHelper isValue:__node name:@"customer_Name"])
                {
                    self.customer_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"customer_Address1"])
             {
                if([SAPHelper isValue:__node name:@"customer_Address1"])
                {
                    self.customer_Address1 = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"city"])
             {
                if([SAPHelper isValue:__node name:@"city"])
                {
                    self.city = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"state"])
             {
                if([SAPHelper isValue:__node name:@"state"])
                {
                    self.state = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"pin_Code"])
             {
                if([SAPHelper isValue:__node name:@"pin_Code"])
                {
                    self.pin_Code = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"email"])
             {
                if([SAPHelper isValue:__node name:@"email"])
                {
                    self.email = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"contact_Details"])
             {
                if([SAPHelper isValue:__node name:@"contact_Details"])
                {
                    self.contact_Details = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"adults"])
             {
                if([SAPHelper isValue:__node name:@"adults"])
                {
                    self.adults = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"children"])
             {
                if([SAPHelper isValue:__node name:@"children"])
                {
                    self.children = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"infants"])
             {
                if([SAPHelper isValue:__node name:@"infants"])
                {
                    self.infants = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"senior_Citizens"])
             {
                if([SAPHelper isValue:__node name:@"senior_Citizens"])
                {
                    self.senior_Citizens = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"ticket_Cost"])
             {
                if([SAPHelper isValue:__node name:@"ticket_Cost"])
                {
                    self.ticket_Cost = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"package_Cost"])
             {
                if([SAPHelper isValue:__node name:@"package_Cost"])
                {
                    self.package_Cost = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"total_Cost"])
             {
                if([SAPHelper isValue:__node name:@"total_Cost"])
                {
                    self.total_Cost = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"commission"])
             {
                if([SAPHelper isValue:__node name:@"commission"])
                {
                    self.commission = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"serTax"])
             {
                if([SAPHelper isValue:__node name:@"serTax"])
                {
                    self.serTax = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"TDS"])
             {
                if([SAPHelper isValue:__node name:@"TDS"])
                {
                    self.TDS = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"total_Cost_To_Agent"])
             {
                if([SAPHelper isValue:__node name:@"total_Cost_To_Agent"])
                {
                    self.total_Cost_To_Agent = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"promotion_Amount"])
             {
                if([SAPHelper isValue:__node name:@"promotion_Amount"])
                {
                    self.promotion_Amount = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"net_Amount"])
             {
                if([SAPHelper isValue:__node name:@"net_Amount"])
                {
                    self.net_Amount = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"cancellation_Penalty"])
             {
                if([SAPHelper isValue:__node name:@"cancellation_Penalty"])
                {
                    self.cancellation_Penalty = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"refund_Amount"])
             {
                if([SAPHelper isValue:__node name:@"refund_Amount"])
                {
                    self.refund_Amount = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"promo_Code"])
             {
                if([SAPHelper isValue:__node name:@"promo_Code"])
                {
                    self.promo_Code = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"auto_Promo_code"])
             {
                if([SAPHelper isValue:__node name:@"auto_Promo_code"])
                {
                    self.auto_Promo_code = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"gifted"])
             {
                if([SAPHelper isValue:__node name:@"gifted"])
                {
                    self.gifted = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"gifted_To"])
             {
                if([SAPHelper isValue:__node name:@"gifted_To"])
                {
                    self.gifted_To = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"PG_Name"])
             {
                if([SAPHelper isValue:__node name:@"PG_Name"])
                {
                    self.PG_Name = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"payment_Ref_Id"])
             {
                if([SAPHelper isValue:__node name:@"payment_Ref_Id"])
                {
                    self.payment_Ref_Id = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"order_Ref_Id"])
             {
                if([SAPHelper isValue:__node name:@"order_Ref_Id"])
                {
                    self.order_Ref_Id = [__node stringValue];
                }
                continue;
             }
             if([__node.localName isEqualToString:@"app_Booking"])
             {
                if([SAPHelper isValue:__node name:@"app_Booking"])
                {
                    self.app_Booking = [__node stringValue];
                }
                continue;
             }
        }
     }
}

-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request
{

            
    DDXMLElement* __SL_NoItemElement=[__request writeElement:SL_No type:[NSString class] name:@"SL_No" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SL_NoItemElement!=nil)
    {
        [__SL_NoItemElement setStringValue:self.SL_No];
    }
            
    DDXMLElement* __transaction_DateItemElement=[__request writeElement:transaction_Date type:[NSString class] name:@"transaction_Date" URI:@"" parent:__parent skipNullProperty:NO];
    if(__transaction_DateItemElement!=nil)
    {
        [__transaction_DateItemElement setStringValue:self.transaction_Date];
    }
            
    DDXMLElement* __booking_TimeItemElement=[__request writeElement:booking_Time type:[NSString class] name:@"booking_Time" URI:@"" parent:__parent skipNullProperty:NO];
    if(__booking_TimeItemElement!=nil)
    {
        [__booking_TimeItemElement setStringValue:self.booking_Time];
    }
            
    DDXMLElement* __invoiced_DateItemElement=[__request writeElement:invoiced_Date type:[NSString class] name:@"invoiced_Date" URI:@"" parent:__parent skipNullProperty:NO];
    if(__invoiced_DateItemElement!=nil)
    {
        [__invoiced_DateItemElement setStringValue:self.invoiced_Date];
    }
            
    DDXMLElement* __date_Of_VisitItemElement=[__request writeElement:date_Of_Visit type:[NSString class] name:@"date_Of_Visit" URI:@"" parent:__parent skipNullProperty:NO];
    if(__date_Of_VisitItemElement!=nil)
    {
        [__date_Of_VisitItemElement setStringValue:self.date_Of_Visit];
    }
            
    DDXMLElement* __transaction_TypeItemElement=[__request writeElement:transaction_Type type:[NSString class] name:@"transaction_Type" URI:@"" parent:__parent skipNullProperty:NO];
    if(__transaction_TypeItemElement!=nil)
    {
        [__transaction_TypeItemElement setStringValue:self.transaction_Type];
    }
            
    DDXMLElement* __agent_NameItemElement=[__request writeElement:agent_Name type:[NSString class] name:@"agent_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__agent_NameItemElement!=nil)
    {
        [__agent_NameItemElement setStringValue:self.agent_Name];
    }
            
    DDXMLElement* __PSA_NameItemElement=[__request writeElement:PSA_Name type:[NSString class] name:@"PSA_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__PSA_NameItemElement!=nil)
    {
        [__PSA_NameItemElement setStringValue:self.PSA_Name];
    }
            
    DDXMLElement* __transaction_IDItemElement=[__request writeElement:transaction_ID type:[NSString class] name:@"transaction_ID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__transaction_IDItemElement!=nil)
    {
        [__transaction_IDItemElement setStringValue:self.transaction_ID];
    }
            
    DDXMLElement* __galaxy_IDItemElement=[__request writeElement:galaxy_ID type:[NSString class] name:@"galaxy_ID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__galaxy_IDItemElement!=nil)
    {
        [__galaxy_IDItemElement setStringValue:self.galaxy_ID];
    }
            
    DDXMLElement* __destinationItemElement=[__request writeElement:destination type:[NSString class] name:@"destination" URI:@"" parent:__parent skipNullProperty:NO];
    if(__destinationItemElement!=nil)
    {
        [__destinationItemElement setStringValue:self.destination];
    }
            
    DDXMLElement* __ticket_TypeItemElement=[__request writeElement:ticket_Type type:[NSString class] name:@"ticket_Type" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ticket_TypeItemElement!=nil)
    {
        [__ticket_TypeItemElement setStringValue:self.ticket_Type];
    }
            
    DDXMLElement* __statusItemElement=[__request writeElement:status type:[NSString class] name:@"status" URI:@"" parent:__parent skipNullProperty:NO];
    if(__statusItemElement!=nil)
    {
        [__statusItemElement setStringValue:self.status];
    }
            
    DDXMLElement* __package_CodeItemElement=[__request writeElement:package_Code type:[NSString class] name:@"package_Code" URI:@"" parent:__parent skipNullProperty:NO];
    if(__package_CodeItemElement!=nil)
    {
        [__package_CodeItemElement setStringValue:self.package_Code];
    }
            
    DDXMLElement* __package_NameItemElement=[__request writeElement:package_Name type:[NSString class] name:@"package_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__package_NameItemElement!=nil)
    {
        [__package_NameItemElement setStringValue:self.package_Name];
    }
            
    DDXMLElement* __customer_NameItemElement=[__request writeElement:customer_Name type:[NSString class] name:@"customer_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__customer_NameItemElement!=nil)
    {
        [__customer_NameItemElement setStringValue:self.customer_Name];
    }
            
    DDXMLElement* __customer_Address1ItemElement=[__request writeElement:customer_Address1 type:[NSString class] name:@"customer_Address1" URI:@"" parent:__parent skipNullProperty:NO];
    if(__customer_Address1ItemElement!=nil)
    {
        [__customer_Address1ItemElement setStringValue:self.customer_Address1];
    }
            
    DDXMLElement* __cityItemElement=[__request writeElement:city type:[NSString class] name:@"city" URI:@"" parent:__parent skipNullProperty:NO];
    if(__cityItemElement!=nil)
    {
        [__cityItemElement setStringValue:self.city];
    }
            
    DDXMLElement* __stateItemElement=[__request writeElement:state type:[NSString class] name:@"state" URI:@"" parent:__parent skipNullProperty:NO];
    if(__stateItemElement!=nil)
    {
        [__stateItemElement setStringValue:self.state];
    }
            
    DDXMLElement* __pin_CodeItemElement=[__request writeElement:pin_Code type:[NSString class] name:@"pin_Code" URI:@"" parent:__parent skipNullProperty:NO];
    if(__pin_CodeItemElement!=nil)
    {
        [__pin_CodeItemElement setStringValue:self.pin_Code];
    }
            
    DDXMLElement* __emailItemElement=[__request writeElement:email type:[NSString class] name:@"email" URI:@"" parent:__parent skipNullProperty:NO];
    if(__emailItemElement!=nil)
    {
        [__emailItemElement setStringValue:self.email];
    }
            
    DDXMLElement* __contact_DetailsItemElement=[__request writeElement:contact_Details type:[NSString class] name:@"contact_Details" URI:@"" parent:__parent skipNullProperty:NO];
    if(__contact_DetailsItemElement!=nil)
    {
        [__contact_DetailsItemElement setStringValue:self.contact_Details];
    }
            
    DDXMLElement* __adultsItemElement=[__request writeElement:adults type:[NSString class] name:@"adults" URI:@"" parent:__parent skipNullProperty:NO];
    if(__adultsItemElement!=nil)
    {
        [__adultsItemElement setStringValue:self.adults];
    }
            
    DDXMLElement* __childrenItemElement=[__request writeElement:children type:[NSString class] name:@"children" URI:@"" parent:__parent skipNullProperty:NO];
    if(__childrenItemElement!=nil)
    {
        [__childrenItemElement setStringValue:self.children];
    }
            
    DDXMLElement* __infantsItemElement=[__request writeElement:infants type:[NSString class] name:@"infants" URI:@"" parent:__parent skipNullProperty:NO];
    if(__infantsItemElement!=nil)
    {
        [__infantsItemElement setStringValue:self.infants];
    }
            
    DDXMLElement* __senior_CitizensItemElement=[__request writeElement:senior_Citizens type:[NSString class] name:@"senior_Citizens" URI:@"" parent:__parent skipNullProperty:NO];
    if(__senior_CitizensItemElement!=nil)
    {
        [__senior_CitizensItemElement setStringValue:self.senior_Citizens];
    }
            
    DDXMLElement* __ticket_CostItemElement=[__request writeElement:ticket_Cost type:[NSString class] name:@"ticket_Cost" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ticket_CostItemElement!=nil)
    {
        [__ticket_CostItemElement setStringValue:self.ticket_Cost];
    }
            
    DDXMLElement* __package_CostItemElement=[__request writeElement:package_Cost type:[NSString class] name:@"package_Cost" URI:@"" parent:__parent skipNullProperty:NO];
    if(__package_CostItemElement!=nil)
    {
        [__package_CostItemElement setStringValue:self.package_Cost];
    }
            
    DDXMLElement* __total_CostItemElement=[__request writeElement:total_Cost type:[NSString class] name:@"total_Cost" URI:@"" parent:__parent skipNullProperty:NO];
    if(__total_CostItemElement!=nil)
    {
        [__total_CostItemElement setStringValue:self.total_Cost];
    }
            
    DDXMLElement* __commissionItemElement=[__request writeElement:commission type:[NSString class] name:@"commission" URI:@"" parent:__parent skipNullProperty:NO];
    if(__commissionItemElement!=nil)
    {
        [__commissionItemElement setStringValue:self.commission];
    }
            
    DDXMLElement* __serTaxItemElement=[__request writeElement:serTax type:[NSString class] name:@"serTax" URI:@"" parent:__parent skipNullProperty:NO];
    if(__serTaxItemElement!=nil)
    {
        [__serTaxItemElement setStringValue:self.serTax];
    }
            
    DDXMLElement* __TDSItemElement=[__request writeElement:TDS type:[NSString class] name:@"TDS" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TDSItemElement!=nil)
    {
        [__TDSItemElement setStringValue:self.TDS];
    }
            
    DDXMLElement* __total_Cost_To_AgentItemElement=[__request writeElement:total_Cost_To_Agent type:[NSString class] name:@"total_Cost_To_Agent" URI:@"" parent:__parent skipNullProperty:NO];
    if(__total_Cost_To_AgentItemElement!=nil)
    {
        [__total_Cost_To_AgentItemElement setStringValue:self.total_Cost_To_Agent];
    }
            
    DDXMLElement* __promotion_AmountItemElement=[__request writeElement:promotion_Amount type:[NSString class] name:@"promotion_Amount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__promotion_AmountItemElement!=nil)
    {
        [__promotion_AmountItemElement setStringValue:self.promotion_Amount];
    }
            
    DDXMLElement* __net_AmountItemElement=[__request writeElement:net_Amount type:[NSString class] name:@"net_Amount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__net_AmountItemElement!=nil)
    {
        [__net_AmountItemElement setStringValue:self.net_Amount];
    }
            
    DDXMLElement* __cancellation_PenaltyItemElement=[__request writeElement:cancellation_Penalty type:[NSString class] name:@"cancellation_Penalty" URI:@"" parent:__parent skipNullProperty:NO];
    if(__cancellation_PenaltyItemElement!=nil)
    {
        [__cancellation_PenaltyItemElement setStringValue:self.cancellation_Penalty];
    }
            
    DDXMLElement* __refund_AmountItemElement=[__request writeElement:refund_Amount type:[NSString class] name:@"refund_Amount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__refund_AmountItemElement!=nil)
    {
        [__refund_AmountItemElement setStringValue:self.refund_Amount];
    }
            
    DDXMLElement* __promo_CodeItemElement=[__request writeElement:promo_Code type:[NSString class] name:@"promo_Code" URI:@"" parent:__parent skipNullProperty:NO];
    if(__promo_CodeItemElement!=nil)
    {
        [__promo_CodeItemElement setStringValue:self.promo_Code];
    }
            
    DDXMLElement* __auto_Promo_codeItemElement=[__request writeElement:auto_Promo_code type:[NSString class] name:@"auto_Promo_code" URI:@"" parent:__parent skipNullProperty:NO];
    if(__auto_Promo_codeItemElement!=nil)
    {
        [__auto_Promo_codeItemElement setStringValue:self.auto_Promo_code];
    }
            
    DDXMLElement* __giftedItemElement=[__request writeElement:gifted type:[NSString class] name:@"gifted" URI:@"" parent:__parent skipNullProperty:NO];
    if(__giftedItemElement!=nil)
    {
        [__giftedItemElement setStringValue:self.gifted];
    }
            
    DDXMLElement* __gifted_ToItemElement=[__request writeElement:gifted_To type:[NSString class] name:@"gifted_To" URI:@"" parent:__parent skipNullProperty:NO];
    if(__gifted_ToItemElement!=nil)
    {
        [__gifted_ToItemElement setStringValue:self.gifted_To];
    }
            
    DDXMLElement* __PG_NameItemElement=[__request writeElement:PG_Name type:[NSString class] name:@"PG_Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__PG_NameItemElement!=nil)
    {
        [__PG_NameItemElement setStringValue:self.PG_Name];
    }
            
    DDXMLElement* __payment_Ref_IdItemElement=[__request writeElement:payment_Ref_Id type:[NSString class] name:@"payment_Ref_Id" URI:@"" parent:__parent skipNullProperty:NO];
    if(__payment_Ref_IdItemElement!=nil)
    {
        [__payment_Ref_IdItemElement setStringValue:self.payment_Ref_Id];
    }
            
    DDXMLElement* __order_Ref_IdItemElement=[__request writeElement:order_Ref_Id type:[NSString class] name:@"order_Ref_Id" URI:@"" parent:__parent skipNullProperty:NO];
    if(__order_Ref_IdItemElement!=nil)
    {
        [__order_Ref_IdItemElement setStringValue:self.order_Ref_Id];
    }
            
    DDXMLElement* __app_BookingItemElement=[__request writeElement:app_Booking type:[NSString class] name:@"app_Booking" URI:@"" parent:__parent skipNullProperty:NO];
    if(__app_BookingItemElement!=nil)
    {
        [__app_BookingItemElement setStringValue:self.app_Booking];
    }


}
@end
