//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "SAPRequestResultHandler.h"
#import "DDXML.h"



@interface SAPReportItemDetail : NSObject <SAPISerializableObject>


@property (retain,nonatomic,getter=getSL_No) NSString* SL_No;

@property (retain,nonatomic,getter=getTransaction_Date) NSString* transaction_Date;

@property (retain,nonatomic,getter=getBooking_Time) NSString* booking_Time;

@property (retain,nonatomic,getter=getInvoiced_Date) NSString* invoiced_Date;

@property (retain,nonatomic,getter=getDate_Of_Visit) NSString* date_Of_Visit;

@property (retain,nonatomic,getter=getTransaction_Type) NSString* transaction_Type;

@property (retain,nonatomic,getter=getAgent_Name) NSString* agent_Name;

@property (retain,nonatomic,getter=getPSA_Name) NSString* PSA_Name;

@property (retain,nonatomic,getter=getTransaction_ID) NSString* transaction_ID;

@property (retain,nonatomic,getter=getGalaxy_ID) NSString* galaxy_ID;

@property (retain,nonatomic,getter=getDestination) NSString* destination;

@property (retain,nonatomic,getter=getTicket_Type) NSString* ticket_Type;

@property (retain,nonatomic,getter=getStatus) NSString* status;

@property (retain,nonatomic,getter=getPackage_Code) NSString* package_Code;

@property (retain,nonatomic,getter=getPackage_Name) NSString* package_Name;

@property (retain,nonatomic,getter=getCustomer_Name) NSString* customer_Name;

@property (retain,nonatomic,getter=getCustomer_Address1) NSString* customer_Address1;

@property (retain,nonatomic,getter=getCity) NSString* city;

@property (retain,nonatomic,getter=getState) NSString* state;

@property (retain,nonatomic,getter=getPin_Code) NSString* pin_Code;

@property (retain,nonatomic,getter=getEmail) NSString* email;

@property (retain,nonatomic,getter=getContact_Details) NSString* contact_Details;

@property (retain,nonatomic,getter=getAdults) NSString* adults;

@property (retain,nonatomic,getter=getChildren) NSString* children;

@property (retain,nonatomic,getter=getInfants) NSString* infants;

@property (retain,nonatomic,getter=getSenior_Citizens) NSString* senior_Citizens;

@property (retain,nonatomic,getter=getTicket_Cost) NSString* ticket_Cost;

@property (retain,nonatomic,getter=getPackage_Cost) NSString* package_Cost;

@property (retain,nonatomic,getter=getTotal_Cost) NSString* total_Cost;

@property (retain,nonatomic,getter=getCommission) NSString* commission;

@property (retain,nonatomic,getter=getSerTax) NSString* serTax;

@property (retain,nonatomic,getter=getTDS) NSString* TDS;

@property (retain,nonatomic,getter=getTotal_Cost_To_Agent) NSString* total_Cost_To_Agent;

@property (retain,nonatomic,getter=getPromotion_Amount) NSString* promotion_Amount;

@property (retain,nonatomic,getter=getNet_Amount) NSString* net_Amount;

@property (retain,nonatomic,getter=getCancellation_Penalty) NSString* cancellation_Penalty;

@property (retain,nonatomic,getter=getRefund_Amount) NSString* refund_Amount;

@property (retain,nonatomic,getter=getPromo_Code) NSString* promo_Code;

@property (retain,nonatomic,getter=getAuto_Promo_code) NSString* auto_Promo_code;

@property (retain,nonatomic,getter=getGifted) NSString* gifted;

@property (retain,nonatomic,getter=getGifted_To) NSString* gifted_To;

@property (retain,nonatomic,getter=getPG_Name) NSString* PG_Name;

@property (retain,nonatomic,getter=getPayment_Ref_Id) NSString* payment_Ref_Id;

@property (retain,nonatomic,getter=getOrder_Ref_Id) NSString* order_Ref_Id;

@property (retain,nonatomic,getter=getApp_Booking) NSString* app_Booking;
-(id)init;
-(void)loadWithXml: (DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
+(SAPReportItemDetail*) createWithXml:(DDXMLElement*)__node __request:(SAPRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(SAPRequestResultHandler*) __request;
@end