//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import "SAPSoapError.h"

@implementation SAPSoapError
@synthesize Details;

-(id)initWithDetails:(NSString*) faultString details:(id)details
{
    if(self = [self initWithDomain:faultString code:0 userInfo:nil])
    {
        self.Details=details;
    }
    return self;
}
@end