//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.0.5
//
// Created by Quasar Development at 29/11/2016
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
    
@interface SAPSoapError : NSError

@property (retain,nonatomic) id Details;
    
-(id)initWithDetails:(NSString*) faultString details:(id)details;
@end
